/gps/particle e+
/gps/number 1
/gps/direction 0 0 -0.932115
/gps/ene/mono 3.53868 MeV
/gps/position 0. 0. -321.088 m
/run/beamOn 1
/gps/particle e+
/gps/number 1
/gps/direction 0 0 -0.987532
/gps/ene/mono 4.36823 MeV
/gps/position 0. 0. -337.789 m
/run/beamOn 1
/gps/particle e+
/gps/number 1
/gps/direction 0 0 -0.89901
/gps/ene/mono 0.718419 MeV
/gps/position 0. 0. -301.543 m
/run/beamOn 1
/gps/particle e+
/gps/number 1
/gps/direction 0 0 -0.995955
/gps/ene/mono 2.86743 MeV
/gps/position 0. 0. -231.273 m
/run/beamOn 1
/gps/particle e+
/gps/number 1
/gps/direction 0 0 -0.970326
/gps/ene/mono 5.06088 MeV
/gps/position 0. 0. -210.813 m
/run/beamOn 1
/gps/particle e+
/gps/number 1
/gps/direction 0 0 -0.765041
/gps/ene/mono 0.551401 MeV
/gps/position 0. 0. -333.928 m
/run/beamOn 1
/gps/particle e+
/gps/number 1
/gps/direction 0 0 -0.893083
/gps/ene/mono 7.28255 MeV
/gps/position 0. 0. -320.303 m
/run/beamOn 1
/gps/particle e+
/gps/number 1
/gps/direction 0 0 -0.873431
/gps/ene/mono 3.24371 MeV
/gps/position 0. 0. -333.602 m
/run/beamOn 1
/gps/particle e+
/gps/number 1
/gps/direction 0 0 -0.810824
/gps/ene/mono 3.59925 MeV
/gps/position 0. 0. -328.649 m
/run/beamOn 1
/gps/particle e+
/gps/number 1
/gps/direction 0 0 0.0595318
/gps/ene/mono 0.234613 MeV
/gps/position 0. 0. -322.286 m
/run/beamOn 1
/gps/particle e+
/gps/number 1
/gps/direction 0 0 -0.255534
/gps/ene/mono 0.185162 MeV
/gps/position 0. 0. -326.045 m
/run/beamOn 1
/gps/particle e+
/gps/number 1
/gps/direction 0 0 -0.829351
/gps/ene/mono 3.06809 MeV
/gps/position 0. 0. -315.242 m
/run/beamOn 1
/gps/particle e+
/gps/number 1
/gps/direction 0 0 -0.885117
/gps/ene/mono 2.45046 MeV
/gps/position 0. 0. -339.396 m
/run/beamOn 1
/gps/particle e+
/gps/number 1
/gps/direction 0 0 -0.899847
/gps/ene/mono 3.50967 MeV
/gps/position 0. 0. -299.914 m
/run/beamOn 1
/gps/particle e+
/gps/number 1
/gps/direction 0 0 -0.946144
/gps/ene/mono 3.2438 MeV
/gps/position 0. 0. -292.744 m
/run/beamOn 1
/gps/particle e+
/gps/number 1
/gps/direction 0 0 -0.955604
/gps/ene/mono 11.604 MeV
/gps/position 0. 0. -311.71 m
/run/beamOn 1
/gps/particle e+
/gps/number 1
/gps/direction 0 0 -0.985905
/gps/ene/mono 14.4084 MeV
/gps/position 0. 0. -308.618 m
/run/beamOn 1
/gps/particle e+
/gps/number 1
/gps/direction 0 0 -0.980654
/gps/ene/mono 3.5225 MeV
/gps/position 0. 0. -265.585 m
/run/beamOn 1
/gps/particle e+
/gps/number 1
/gps/direction 0 0 -0.951964
/gps/ene/mono 1.87293 MeV
/gps/position 0. 0. -278.895 m
/run/beamOn 1
/gps/particle e+
/gps/number 1
/gps/direction 0 0 -0.470566
/gps/ene/mono 0.56248 MeV
/gps/position 0. 0. -341.229 m
/run/beamOn 1
/gps/particle e+
/gps/number 1
/gps/direction 0 0 -0.935538
/gps/ene/mono 0.891915 MeV
/gps/position 0. 0. -174.384 m
/run/beamOn 1
/gps/particle e+
/gps/number 1
/gps/direction 0 0 -0.838711
/gps/ene/mono 1.82635 MeV
/gps/position 0. 0. -306.875 m
/run/beamOn 1
/gps/particle e+
/gps/number 1
/gps/direction 0 0 -0.89249
/gps/ene/mono 3.42377 MeV
/gps/position 0. 0. -332.286 m
/run/beamOn 1
/gps/particle e+
/gps/number 1
/gps/direction 0 0 -0.987885
/gps/ene/mono 16.4679 MeV
/gps/position 0. 0. -291.433 m
/run/beamOn 1
/gps/particle e+
/gps/number 1
/gps/direction 0 0 -0.993561
/gps/ene/mono 2.27106 MeV
/gps/position 0. 0. -293.23 m
/run/beamOn 1
/gps/particle e+
/gps/number 1
/gps/direction 0 0 -0.991207
/gps/ene/mono 2.86649 MeV
/gps/position 0. 0. -246.845 m
/run/beamOn 1
/gps/particle e+
/gps/number 1
/gps/direction 0 0 -0.34881
/gps/ene/mono 2.41224 MeV
/gps/position 0. 0. -226.505 m
/run/beamOn 1
/gps/particle e+
/gps/number 1
/gps/direction 0 0 -0.671921
/gps/ene/mono 4.15844 MeV
/gps/position 0. 0. -334.947 m
/run/beamOn 1
/gps/particle e+
/gps/number 1
/gps/direction 0 0 -0.99585
/gps/ene/mono 2.95812 MeV
/gps/position 0. 0. -289.143 m
/run/beamOn 1
/gps/particle e+
/gps/number 1
/gps/direction 0 0 -0.999039
/gps/ene/mono 9.86932 MeV
/gps/position 0. 0. -341.971 m
/run/beamOn 1
/gps/particle e+
/gps/number 1
/gps/direction 0 0 -0.954008
/gps/ene/mono 3.15386 MeV
/gps/position 0. 0. -161.384 m
/run/beamOn 1
/gps/particle e+
/gps/number 1
/gps/direction 0 0 -0.982614
/gps/ene/mono 2.14564 MeV
/gps/position 0. 0. -348.959 m
/run/beamOn 1
/gps/particle e+
/gps/number 1
/gps/direction 0 0 -0.829153
/gps/ene/mono 0.527558 MeV
/gps/position 0. 0. -240.668 m
/run/beamOn 1
/gps/particle e+
/gps/number 1
/gps/direction 0 0 -0.956316
/gps/ene/mono 3.10642 MeV
/gps/position 0. 0. -281.352 m
/run/beamOn 1
/gps/particle e+
/gps/number 1
/gps/direction 0 0 -0.99553
/gps/ene/mono 9.18403 MeV
/gps/position 0. 0. -291.168 m
/run/beamOn 1
/gps/particle e+
/gps/number 1
/gps/direction 0 0 -0.959356
/gps/ene/mono 1.79747 MeV
/gps/position 0. 0. -254.634 m
/run/beamOn 1
/gps/particle e+
/gps/number 1
/gps/direction 0 0 -0.977616
/gps/ene/mono 10.0332 MeV
/gps/position 0. 0. -239.427 m
/run/beamOn 1
