/gps/particle electron
/gps/number 1
/gps/direction 0 0 -0.610603
/gps/ene/mono 0.268883 MeV
/gps/position 0. 0. -182.602 m
/run/beamOn 1
/gps/particle electron
/gps/number 1
/gps/direction 0 0 -0.567469
/gps/ene/mono 0.162749 MeV
/gps/position 0. 0. -299.337 m
/run/beamOn 1
/gps/particle electron
/gps/number 1
/gps/direction 0 0 0.919491
/gps/ene/mono 0.277294 MeV
/gps/position 0. 0. 331.136 m
/run/beamOn 1
/gps/particle electron
/gps/number 1
/gps/direction 0 0 0.986733
/gps/ene/mono 0.33704 MeV
/gps/position 0. 0. 31.2386 m
/run/beamOn 1
/gps/particle electron
/gps/number 1
/gps/direction 0 0 -0.383108
/gps/ene/mono 0.21942 MeV
/gps/position 0. 0. -227.978 m
/run/beamOn 1
/gps/particle electron
/gps/number 1
/gps/direction 0 0 0.939632
/gps/ene/mono 0.221762 MeV
/gps/position 0. 0. 90.6831 m
/run/beamOn 1
/gps/particle electron
/gps/number 1
/gps/direction 0 0 -0.0318234
/gps/ene/mono 0.122366 MeV
/gps/position 0. 0. -299.131 m
/run/beamOn 1
/gps/particle electron
/gps/number 1
/gps/direction 0 0 0.989342
/gps/ene/mono 0.366179 MeV
/gps/position 0. 0. -288.362 m
/run/beamOn 1
/gps/particle electron
/gps/number 1
/gps/direction 0 0 -0.910214
/gps/ene/mono 0.32885 MeV
/gps/position 0. 0. -311.086 m
/run/beamOn 1
/gps/particle electron
/gps/number 1
/gps/direction 0 0 0.872165
/gps/ene/mono 0.326505 MeV
/gps/position 0. 0. -288.859 m
/run/beamOn 1
/gps/particle electron
/gps/number 1
/gps/direction 0 0 0.976601
/gps/ene/mono 0.116685 MeV
/gps/position 0. 0. -123.304 m
/run/beamOn 1
/gps/particle electron
/gps/number 1
/gps/direction 0 0 0.227048
/gps/ene/mono 0.213382 MeV
/gps/position 0. 0. -128.48 m
/run/beamOn 1
/gps/particle electron
/gps/number 1
/gps/direction 0 0 0.638931
/gps/ene/mono 0.27223 MeV
/gps/position 0. 0. -221.372 m
/run/beamOn 1
/gps/particle electron
/gps/number 1
/gps/direction 0 0 0.28601
/gps/ene/mono 0.147333 MeV
/gps/position 0. 0. -161.446 m
/run/beamOn 1
/gps/particle electron
/gps/number 1
/gps/direction 0 0 0.316047
/gps/ene/mono 0.141538 MeV
/gps/position 0. 0. -127.526 m
/run/beamOn 1
/gps/particle electron
/gps/number 1
/gps/direction 0 0 0.374028
/gps/ene/mono 0.138383 MeV
/gps/position 0. 0. -126.381 m
/run/beamOn 1
/gps/particle electron
/gps/number 1
/gps/direction 0 0 0.436826
/gps/ene/mono 0.217288 MeV
/gps/position 0. 0. -83.0726 m
/run/beamOn 1
/gps/particle electron
/gps/number 1
/gps/direction 0 0 0.230057
/gps/ene/mono 0.150836 MeV
/gps/position 0. 0. -33.6247 m
/run/beamOn 1
/gps/particle electron
/gps/number 1
/gps/direction 0 0 0.463652
/gps/ene/mono 0.22885 MeV
/gps/position 0. 0. -26.1451 m
/run/beamOn 1
/gps/particle electron
/gps/number 1
/gps/direction 0 0 0.616339
/gps/ene/mono 0.340146 MeV
/gps/position 0. 0. -26.0951 m
/run/beamOn 1
/gps/particle electron
/gps/number 1
/gps/direction 0 0 0.368114
/gps/ene/mono 0.111746 MeV
/gps/position 0. 0. -25.8356 m
/run/beamOn 1
/gps/particle electron
/gps/number 1
/gps/direction 0 0 0.549987
/gps/ene/mono 0.223907 MeV
/gps/position 0. 0. 60.4786 m
/run/beamOn 1
/gps/particle electron
/gps/number 1
/gps/direction 0 0 0.646534
/gps/ene/mono 0.729666 MeV
/gps/position 0. 0. 115.017 m
/run/beamOn 1
/gps/particle electron
/gps/number 1
/gps/direction 0 0 0.385359
/gps/ene/mono 0.136224 MeV
/gps/position 0. 0. 117.912 m
/run/beamOn 1
/gps/particle electron
/gps/number 1
/gps/direction 0 0 0.931785
/gps/ene/mono 5.37945 MeV
/gps/position 0. 0. 155.689 m
/run/beamOn 1
/gps/particle electron
/gps/number 1
/gps/direction 0 0 0.53981
/gps/ene/mono 0.453665 MeV
/gps/position 0. 0. 159.682 m
/run/beamOn 1
/gps/particle electron
/gps/number 1
/gps/direction 0 0 0.322137
/gps/ene/mono 0.180926 MeV
/gps/position 0. 0. 188.09 m
/run/beamOn 1
/gps/particle electron
/gps/number 1
/gps/direction 0 0 0.450472
/gps/ene/mono 0.249363 MeV
/gps/position 0. 0. 192.136 m
/run/beamOn 1
/gps/particle electron
/gps/number 1
/gps/direction 0 0 0.285173
/gps/ene/mono 0.110373 MeV
/gps/position 0. 0. 243.272 m
/run/beamOn 1
/gps/particle electron
/gps/number 1
/gps/direction 0 0 0.585916
/gps/ene/mono 0.395238 MeV
/gps/position 0. 0. 276.615 m
/run/beamOn 1
/gps/particle electron
/gps/number 1
/gps/direction 0 0 0.492941
/gps/ene/mono 0.153926 MeV
/gps/position 0. 0. 285.965 m
/run/beamOn 1
/gps/particle electron
/gps/number 1
/gps/direction 0 0 0.879761
/gps/ene/mono 6.80467 MeV
/gps/position 0. 0. 298.066 m
/run/beamOn 1
/gps/particle electron
/gps/number 1
/gps/direction 0 0 0.523437
/gps/ene/mono 0.206229 MeV
/gps/position 0. 0. 299.853 m
/run/beamOn 1
/gps/particle electron
/gps/number 1
/gps/direction 0 0 0.359577
/gps/ene/mono 0.174195 MeV
/gps/position 0. 0. 342.141 m
/run/beamOn 1
/gps/particle electron
/gps/number 1
/gps/direction 0 0 0.434472
/gps/ene/mono 0.215488 MeV
/gps/position 0. 0. -12.0008 m
/run/beamOn 1
/gps/particle electron
/gps/number 1
/gps/direction 0 0 -0.999337
/gps/ene/mono 0.104119 MeV
/gps/position 0. 0. -281.603 m
/run/beamOn 1
