/gps/particle e+
/gps/number 1
/gps/direction 0 0 -0.979141
/gps/ene/mono 6.90411 MeV
/gps/position 0. 0. -158.971 m
/run/beamOn 1
/gps/particle e+
/gps/number 1
/gps/direction 0 0 -0.892269
/gps/ene/mono 0.566015 MeV
/gps/position 0. 0. -317.933 m
/run/beamOn 1
/gps/particle e+
/gps/number 1
/gps/direction 0 0 -0.985126
/gps/ene/mono 3.97896 MeV
/gps/position 0. 0. -271.052 m
/run/beamOn 1
/gps/particle e+
/gps/number 1
/gps/direction 0 0 -0.854698
/gps/ene/mono 2.78506 MeV
/gps/position 0. 0. -304.655 m
/run/beamOn 1
/gps/particle e+
/gps/number 1
/gps/direction 0 0 -0.984919
/gps/ene/mono 7.55003 MeV
/gps/position 0. 0. -306.278 m
/run/beamOn 1
/gps/particle e+
/gps/number 1
/gps/direction 0 0 -0.980428
/gps/ene/mono 3.38633 MeV
/gps/position 0. 0. -272.276 m
/run/beamOn 1
/gps/particle e+
/gps/number 1
/gps/direction 0 0 -0.940888
/gps/ene/mono 4.67358 MeV
/gps/position 0. 0. -320.497 m
/run/beamOn 1
/gps/particle e+
/gps/number 1
/gps/direction 0 0 -0.885435
/gps/ene/mono 1.72063 MeV
/gps/position 0. 0. -302.312 m
/run/beamOn 1
/gps/particle e+
/gps/number 1
/gps/direction 0 0 -0.926045
/gps/ene/mono 0.232951 MeV
/gps/position 0. 0. -269.471 m
/run/beamOn 1
/gps/particle e+
/gps/number 1
/gps/direction 0 0 -0.974773
/gps/ene/mono 2.82969 MeV
/gps/position 0. 0. -211.449 m
/run/beamOn 1
/gps/particle e+
/gps/number 1
/gps/direction 0 0 -0.675868
/gps/ene/mono 1.03226 MeV
/gps/position 0. 0. -228.915 m
/run/beamOn 1
/gps/particle e+
/gps/number 1
/gps/direction 0 0 -0.828051
/gps/ene/mono 0.472299 MeV
/gps/position 0. 0. -338.584 m
/run/beamOn 1
/gps/particle e+
/gps/number 1
/gps/direction 0 0 -0.943207
/gps/ene/mono 5.05003 MeV
/gps/position 0. 0. -273.225 m
/run/beamOn 1
/gps/particle e+
/gps/number 1
/gps/direction 0 0 -0.88596
/gps/ene/mono 0.59662 MeV
/gps/position 0. 0. -348.098 m
/run/beamOn 1
/gps/particle e+
/gps/number 1
/gps/direction 0 0 -0.968061
/gps/ene/mono 4.7363 MeV
/gps/position 0. 0. -296.258 m
/run/beamOn 1
/gps/particle e+
/gps/number 1
/gps/direction 0 0 -0.843707
/gps/ene/mono 1.02214 MeV
/gps/position 0. 0. -291.871 m
/run/beamOn 1
/gps/particle e+
/gps/number 1
/gps/direction 0 0 -0.803156
/gps/ene/mono 2.54634 MeV
/gps/position 0. 0. -327.429 m
/run/beamOn 1
/gps/particle e+
/gps/number 1
/gps/direction 0 0 -0.577333
/gps/ene/mono 0.699132 MeV
/gps/position 0. 0. -314.452 m
/run/beamOn 1
/gps/particle e+
/gps/number 1
/gps/direction 0 0 -0.930703
/gps/ene/mono 1.63801 MeV
/gps/position 0. 0. -336.386 m
/run/beamOn 1
/gps/particle e+
/gps/number 1
/gps/direction 0 0 -0.970976
/gps/ene/mono 0.897896 MeV
/gps/position 0. 0. -236.002 m
/run/beamOn 1
/gps/particle e+
/gps/number 1
/gps/direction 0 0 -0.971593
/gps/ene/mono 19.4846 MeV
/gps/position 0. 0. -349.095 m
/run/beamOn 1
/gps/particle e+
/gps/number 1
/gps/direction 0 0 0.556482
/gps/ene/mono 0.389875 MeV
/gps/position 0. 0. -336.836 m
/run/beamOn 1
/gps/particle e+
/gps/number 1
/gps/direction 0 0 -0.999635
/gps/ene/mono 7.73397 MeV
/gps/position 0. 0. -337.653 m
/run/beamOn 1
/gps/particle e+
/gps/number 1
/gps/direction 0 0 -0.135654
/gps/ene/mono 1.10051 MeV
/gps/position 0. 0. -342.903 m
/run/beamOn 1
/gps/particle e+
/gps/number 1
/gps/direction 0 0 -0.980888
/gps/ene/mono 2.38077 MeV
/gps/position 0. 0. -343.594 m
/run/beamOn 1
/gps/particle e+
/gps/number 1
/gps/direction 0 0 -0.926783
/gps/ene/mono 1.35683 MeV
/gps/position 0. 0. -310.338 m
/run/beamOn 1
/gps/particle e+
/gps/number 1
/gps/direction 0 0 0.240285
/gps/ene/mono 1.19033 MeV
/gps/position 0. 0. -270.285 m
/run/beamOn 1
/gps/particle e+
/gps/number 1
/gps/direction 0 0 -0.949506
/gps/ene/mono 3.81755 MeV
/gps/position 0. 0. -254.298 m
/run/beamOn 1
/gps/particle e+
/gps/number 1
/gps/direction 0 0 -0.901202
/gps/ene/mono 0.697911 MeV
/gps/position 0. 0. -220.928 m
/run/beamOn 1
/gps/particle e+
/gps/number 1
/gps/direction 0 0 -0.957445
/gps/ene/mono 5.40318 MeV
/gps/position 0. 0. -324.157 m
/run/beamOn 1
/gps/particle e+
/gps/number 1
/gps/direction 0 0 -0.969745
/gps/ene/mono 2.05006 MeV
/gps/position 0. 0. -317.315 m
/run/beamOn 1
/gps/particle e+
/gps/number 1
/gps/direction 0 0 -0.854846
/gps/ene/mono 1.80059 MeV
/gps/position 0. 0. -347.205 m
/run/beamOn 1
