/gps/particle electron
/gps/number 1
/gps/direction 0 0 -0.283765
/gps/ene/mono 0.135128 MeV
/gps/position 0. 0. -277.227 m
/run/beamOn 1
/gps/particle electron
/gps/number 1
/gps/direction 0 0 0.398324
/gps/ene/mono 0.186085 MeV
/gps/position 0. 0. -194.487 m
/run/beamOn 1
/gps/particle electron
/gps/number 1
/gps/direction 0 0 -0.483604
/gps/ene/mono 0.138843 MeV
/gps/position 0. 0. -222.359 m
/run/beamOn 1
/gps/particle electron
/gps/number 1
/gps/direction 0 0 0.0922641
/gps/ene/mono 0.141812 MeV
/gps/position 0. 0. -227.538 m
/run/beamOn 1
/gps/particle electron
/gps/number 1
/gps/direction 0 0 0.465961
/gps/ene/mono 0.382696 MeV
/gps/position 0. 0. -212.902 m
/run/beamOn 1
/gps/particle electron
/gps/number 1
/gps/direction 0 0 0.49324
/gps/ene/mono 0.163935 MeV
/gps/position 0. 0. -202.129 m
/run/beamOn 1
/gps/particle electron
/gps/number 1
/gps/direction 0 0 0.759725
/gps/ene/mono 0.598904 MeV
/gps/position 0. 0. -198.647 m
/run/beamOn 1
/gps/particle electron
/gps/number 1
/gps/direction 0 0 0.592392
/gps/ene/mono 0.154205 MeV
/gps/position 0. 0. -182.288 m
/run/beamOn 1
/gps/particle electron
/gps/number 1
/gps/direction 0 0 0.230144
/gps/ene/mono 0.31939 MeV
/gps/position 0. 0. -171.636 m
/run/beamOn 1
/gps/particle electron
/gps/number 1
/gps/direction 0 0 0.00923332
/gps/ene/mono 0.220781 MeV
/gps/position 0. 0. -129.628 m
/run/beamOn 1
/gps/particle electron
/gps/number 1
/gps/direction 0 0 0.552846
/gps/ene/mono 2.18097 MeV
/gps/position 0. 0. -112.118 m
/run/beamOn 1
/gps/particle electron
/gps/number 1
/gps/direction 0 0 0.5613
/gps/ene/mono 0.584029 MeV
/gps/position 0. 0. -81.7679 m
/run/beamOn 1
/gps/particle electron
/gps/number 1
/gps/direction 0 0 0.451005
/gps/ene/mono 0.167447 MeV
/gps/position 0. 0. -68.9877 m
/run/beamOn 1
/gps/particle electron
/gps/number 1
/gps/direction 0 0 0.748297
/gps/ene/mono 0.983005 MeV
/gps/position 0. 0. -7.31226 m
/run/beamOn 1
/gps/particle electron
/gps/number 1
/gps/direction 0 0 0.461737
/gps/ene/mono 0.14739 MeV
/gps/position 0. 0. 40.3221 m
/run/beamOn 1
/gps/particle electron
/gps/number 1
/gps/direction 0 0 0.33779
/gps/ene/mono 0.156818 MeV
/gps/position 0. 0. 80.0006 m
/run/beamOn 1
/gps/particle electron
/gps/number 1
/gps/direction 0 0 0.31468
/gps/ene/mono 0.176686 MeV
/gps/position 0. 0. 119.986 m
/run/beamOn 1
/gps/particle electron
/gps/number 1
/gps/direction 0 0 0.544545
/gps/ene/mono 0.136589 MeV
/gps/position 0. 0. 159.301 m
/run/beamOn 1
/gps/particle electron
/gps/number 1
/gps/direction 0 0 0.61578
/gps/ene/mono 0.289176 MeV
/gps/position 0. 0. 179.928 m
/run/beamOn 1
/gps/particle electron
/gps/number 1
/gps/direction 0 0 0.340808
/gps/ene/mono 0.161374 MeV
/gps/position 0. 0. 212.562 m
/run/beamOn 1
/gps/particle electron
/gps/number 1
/gps/direction 0 0 0.282209
/gps/ene/mono 0.14402 MeV
/gps/position 0. 0. 243.128 m
/run/beamOn 1
/gps/particle electron
/gps/number 1
/gps/direction 0 0 0.541975
/gps/ene/mono 0.283904 MeV
/gps/position 0. 0. 252.568 m
/run/beamOn 1
/gps/particle electron
/gps/number 1
/gps/direction 0 0 0.48224
/gps/ene/mono 0.220278 MeV
/gps/position 0. 0. 260.807 m
/run/beamOn 1
/gps/particle electron
/gps/number 1
/gps/direction 0 0 0.54906
/gps/ene/mono 0.34289 MeV
/gps/position 0. 0. 293.431 m
/run/beamOn 1
/gps/particle electron
/gps/number 1
/gps/direction 0 0 0.309714
/gps/ene/mono 0.105599 MeV
/gps/position 0. 0. 302.308 m
/run/beamOn 1
/gps/particle electron
/gps/number 1
/gps/direction 0 0 0.286635
/gps/ene/mono 0.109623 MeV
/gps/position 0. 0. 343.838 m
/run/beamOn 1
/gps/particle electron
/gps/number 1
/gps/direction 0 0 0.999338
/gps/ene/mono 1.92065 MeV
/gps/position 0. 0. 342.457 m
/run/beamOn 1
/gps/particle electron
/gps/number 1
/gps/direction 0 0 0.629065
/gps/ene/mono 0.131724 MeV
/gps/position 0. 0. 109.152 m
/run/beamOn 1
/gps/particle electron
/gps/number 1
/gps/direction 0 0 0.908614
/gps/ene/mono 0.611056 MeV
/gps/position 0. 0. -119.045 m
/run/beamOn 1
/gps/particle electron
/gps/number 1
/gps/direction 0 0 0.419312
/gps/ene/mono 0.659808 MeV
/gps/position 0. 0. 110.276 m
/run/beamOn 1
/gps/particle electron
/gps/number 1
/gps/direction 0 0 0.287422
/gps/ene/mono 0.214774 MeV
/gps/position 0. 0. 117.431 m
/run/beamOn 1
/gps/particle electron
/gps/number 1
/gps/direction 0 0 0.386123
/gps/ene/mono 0.225069 MeV
/gps/position 0. 0. -263.036 m
/run/beamOn 1
/gps/particle electron
/gps/number 1
/gps/direction 0 0 0.986973
/gps/ene/mono 1.30855 MeV
/gps/position 0. 0. -240.825 m
/run/beamOn 1
/gps/particle electron
/gps/number 1
/gps/direction 0 0 0.158193
/gps/ene/mono 0.159764 MeV
/gps/position 0. 0. -229.935 m
/run/beamOn 1
/gps/particle electron
/gps/number 1
/gps/direction 0 0 0.17482
/gps/ene/mono 0.121517 MeV
/gps/position 0. 0. -214.4 m
/run/beamOn 1
/gps/particle electron
/gps/number 1
/gps/direction 0 0 0.633813
/gps/ene/mono 0.568653 MeV
/gps/position 0. 0. -196.778 m
/run/beamOn 1
/gps/particle electron
/gps/number 1
/gps/direction 0 0 0.108715
/gps/ene/mono 0.107978 MeV
/gps/position 0. 0. -188.451 m
/run/beamOn 1
/gps/particle electron
/gps/number 1
/gps/direction 0 0 0.381599
/gps/ene/mono 0.418318 MeV
/gps/position 0. 0. -180.316 m
/run/beamOn 1
/gps/particle electron
/gps/number 1
/gps/direction 0 0 0.342652
/gps/ene/mono 0.172881 MeV
/gps/position 0. 0. -152.504 m
/run/beamOn 1
/gps/particle electron
/gps/number 1
/gps/direction 0 0 0.173488
/gps/ene/mono 0.14158 MeV
/gps/position 0. 0. -151.947 m
/run/beamOn 1
/gps/particle electron
/gps/number 1
/gps/direction 0 0 0.449598
/gps/ene/mono 0.117916 MeV
/gps/position 0. 0. -64.2701 m
/run/beamOn 1
/gps/particle electron
/gps/number 1
/gps/direction 0 0 0.290115
/gps/ene/mono 0.163296 MeV
/gps/position 0. 0. -5.47127 m
/run/beamOn 1
/gps/particle electron
/gps/number 1
/gps/direction 0 0 0.331754
/gps/ene/mono 0.336052 MeV
/gps/position 0. 0. 26.3464 m
/run/beamOn 1
/gps/particle electron
/gps/number 1
/gps/direction 0 0 0.447399
/gps/ene/mono 0.156127 MeV
/gps/position 0. 0. 66.8198 m
/run/beamOn 1
/gps/particle electron
/gps/number 1
/gps/direction 0 0 0.416663
/gps/ene/mono 0.220177 MeV
/gps/position 0. 0. 123.912 m
/run/beamOn 1
/gps/particle electron
/gps/number 1
/gps/direction 0 0 0.631045
/gps/ene/mono 0.302815 MeV
/gps/position 0. 0. 167.735 m
/run/beamOn 1
/gps/particle electron
/gps/number 1
/gps/direction 0 0 0.192158
/gps/ene/mono 0.111999 MeV
/gps/position 0. 0. 176.272 m
/run/beamOn 1
/gps/particle electron
/gps/number 1
/gps/direction 0 0 0.412189
/gps/ene/mono 0.131347 MeV
/gps/position 0. 0. 179.954 m
/run/beamOn 1
/gps/particle electron
/gps/number 1
/gps/direction 0 0 0.323562
/gps/ene/mono 0.137949 MeV
/gps/position 0. 0. 180.752 m
/run/beamOn 1
/gps/particle electron
/gps/number 1
/gps/direction 0 0 0.404391
/gps/ene/mono 0.290355 MeV
/gps/position 0. 0. 232.936 m
/run/beamOn 1
/gps/particle electron
/gps/number 1
/gps/direction 0 0 0.289528
/gps/ene/mono 0.108199 MeV
/gps/position 0. 0. 270.898 m
/run/beamOn 1
/gps/particle electron
/gps/number 1
/gps/direction 0 0 0.559841
/gps/ene/mono 1.07713 MeV
/gps/position 0. 0. 305.513 m
/run/beamOn 1
/gps/particle electron
/gps/number 1
/gps/direction 0 0 0.71757
/gps/ene/mono 0.44427 MeV
/gps/position 0. 0. 305.632 m
/run/beamOn 1
/gps/particle electron
/gps/number 1
/gps/direction 0 0 0.85864
/gps/ene/mono 7.96006 MeV
/gps/position 0. 0. 313.703 m
/run/beamOn 1
/gps/particle electron
/gps/number 1
/gps/direction 0 0 0.594152
/gps/ene/mono 0.361641 MeV
/gps/position 0. 0. 337.944 m
/run/beamOn 1
/gps/particle electron
/gps/number 1
/gps/direction 0 0 0.727174
/gps/ene/mono 0.115225 MeV
/gps/position 0. 0. 147.022 m
/run/beamOn 1
/gps/particle electron
/gps/number 1
/gps/direction 0 0 0.91825
/gps/ene/mono 0.516549 MeV
/gps/position 0. 0. -36.1149 m
/run/beamOn 1
/gps/particle electron
/gps/number 1
/gps/direction 0 0 0.312131
/gps/ene/mono 0.11876 MeV
/gps/position 0. 0. -33.8473 m
/run/beamOn 1
/gps/particle electron
/gps/number 1
/gps/direction 0 0 -0.156374
/gps/ene/mono 0.115269 MeV
/gps/position 0. 0. -17.4124 m
/run/beamOn 1
/gps/particle electron
/gps/number 1
/gps/direction 0 0 0.716994
/gps/ene/mono 0.317996 MeV
/gps/position 0. 0. -5.3838 m
/run/beamOn 1
/gps/particle electron
/gps/number 1
/gps/direction 0 0 0.398734
/gps/ene/mono 0.176119 MeV
/gps/position 0. 0. -3.97001 m
/run/beamOn 1
/gps/particle electron
/gps/number 1
/gps/direction 0 0 0.217676
/gps/ene/mono 1.02129 MeV
/gps/position 0. 0. 1.20259 m
/run/beamOn 1
/gps/particle electron
/gps/number 1
/gps/direction 0 0 0.558002
/gps/ene/mono 0.31213 MeV
/gps/position 0. 0. 45.5564 m
/run/beamOn 1
/gps/particle electron
/gps/number 1
/gps/direction 0 0 0.425434
/gps/ene/mono 0.189498 MeV
/gps/position 0. 0. 153.303 m
/run/beamOn 1
/gps/particle electron
/gps/number 1
/gps/direction 0 0 0.272584
/gps/ene/mono 0.105788 MeV
/gps/position 0. 0. 179.236 m
/run/beamOn 1
/gps/particle electron
/gps/number 1
/gps/direction 0 0 0.637388
/gps/ene/mono 0.818495 MeV
/gps/position 0. 0. 192.378 m
/run/beamOn 1
/gps/particle electron
/gps/number 1
/gps/direction 0 0 0.52015
/gps/ene/mono 0.449628 MeV
/gps/position 0. 0. 252.292 m
/run/beamOn 1
/gps/particle electron
/gps/number 1
/gps/direction 0 0 0.198423
/gps/ene/mono 0.142179 MeV
/gps/position 0. 0. 275.316 m
/run/beamOn 1
/gps/particle electron
/gps/number 1
/gps/direction 0 0 0.907683
/gps/ene/mono 0.102267 MeV
/gps/position 0. 0. 230.168 m
/run/beamOn 1
/gps/particle electron
/gps/number 1
/gps/direction 0 0 0.193866
/gps/ene/mono 0.189493 MeV
/gps/position 0. 0. 236.017 m
/run/beamOn 1
/gps/particle electron
/gps/number 1
/gps/direction 0 0 -0.0394329
/gps/ene/mono 0.304464 MeV
/gps/position 0. 0. -298.873 m
/run/beamOn 1
/gps/particle electron
/gps/number 1
/gps/direction 0 0 0.167782
/gps/ene/mono 0.271246 MeV
/gps/position 0. 0. -290.192 m
/run/beamOn 1
/gps/particle electron
/gps/number 1
/gps/direction 0 0 0.791002
/gps/ene/mono 0.185341 MeV
/gps/position 0. 0. -249.984 m
/run/beamOn 1
/gps/particle electron
/gps/number 1
/gps/direction 0 0 0.390897
/gps/ene/mono 0.11723 MeV
/gps/position 0. 0. -135.947 m
/run/beamOn 1
/gps/particle electron
/gps/number 1
/gps/direction 0 0 0.340023
/gps/ene/mono 0.338296 MeV
/gps/position 0. 0. -122.299 m
/run/beamOn 1
/gps/particle electron
/gps/number 1
/gps/direction 0 0 0.127567
/gps/ene/mono 0.722026 MeV
/gps/position 0. 0. -97.9237 m
/run/beamOn 1
/gps/particle electron
/gps/number 1
/gps/direction 0 0 0.354378
/gps/ene/mono 0.632075 MeV
/gps/position 0. 0. -93.5891 m
/run/beamOn 1
/gps/particle electron
/gps/number 1
/gps/direction 0 0 0.422004
/gps/ene/mono 0.421044 MeV
/gps/position 0. 0. -68.6221 m
/run/beamOn 1
/gps/particle electron
/gps/number 1
/gps/direction 0 0 0.179596
/gps/ene/mono 0.221394 MeV
/gps/position 0. 0. -36.1937 m
/run/beamOn 1
/gps/particle electron
/gps/number 1
/gps/direction 0 0 0.136415
/gps/ene/mono 0.190448 MeV
/gps/position 0. 0. -28.1033 m
/run/beamOn 1
/gps/particle electron
/gps/number 1
/gps/direction 0 0 0.853994
/gps/ene/mono 3.31581 MeV
/gps/position 0. 0. -21.1069 m
/run/beamOn 1
/gps/particle electron
/gps/number 1
/gps/direction 0 0 0.511434
/gps/ene/mono 0.22427 MeV
/gps/position 0. 0. -9.83038 m
/run/beamOn 1
/gps/particle electron
/gps/number 1
/gps/direction 0 0 0.421037
/gps/ene/mono 0.147612 MeV
/gps/position 0. 0. 85.4545 m
/run/beamOn 1
/gps/particle electron
/gps/number 1
/gps/direction 0 0 0.282139
/gps/ene/mono 0.287456 MeV
/gps/position 0. 0. 100.702 m
/run/beamOn 1
/gps/particle electron
/gps/number 1
/gps/direction 0 0 0.563971
/gps/ene/mono 0.277016 MeV
/gps/position 0. 0. 114.583 m
/run/beamOn 1
/gps/particle electron
/gps/number 1
/gps/direction 0 0 0.576149
/gps/ene/mono 0.103167 MeV
/gps/position 0. 0. 127.655 m
/run/beamOn 1
/gps/particle electron
/gps/number 1
/gps/direction 0 0 0.725556
/gps/ene/mono 0.228355 MeV
/gps/position 0. 0. 141.267 m
/run/beamOn 1
/gps/particle electron
/gps/number 1
/gps/direction 0 0 0.11504
/gps/ene/mono 0.142775 MeV
/gps/position 0. 0. 211.782 m
/run/beamOn 1
/gps/particle electron
/gps/number 1
/gps/direction 0 0 0.787443
/gps/ene/mono 0.746733 MeV
/gps/position 0. 0. 225.295 m
/run/beamOn 1
/gps/particle electron
/gps/number 1
/gps/direction 0 0 0.538068
/gps/ene/mono 0.204753 MeV
/gps/position 0. 0. 260.07 m
/run/beamOn 1
/gps/particle electron
/gps/number 1
/gps/direction 0 0 0.353876
/gps/ene/mono 0.292642 MeV
/gps/position 0. 0. 294.457 m
/run/beamOn 1
/gps/particle electron
/gps/number 1
/gps/direction 0 0 0.183867
/gps/ene/mono 0.140674 MeV
/gps/position 0. 0. 311.845 m
/run/beamOn 1
/gps/particle electron
/gps/number 1
/gps/direction 0 0 0.850283
/gps/ene/mono 1.42719 MeV
/gps/position 0. 0. 323.871 m
/run/beamOn 1
/gps/particle electron
/gps/number 1
/gps/direction 0 0 0.71657
/gps/ene/mono 0.18663 MeV
/gps/position 0. 0. -264.329 m
/run/beamOn 1
/gps/particle electron
/gps/number 1
/gps/direction 0 0 0.811781
/gps/ene/mono 0.446875 MeV
/gps/position 0. 0. -217.356 m
/run/beamOn 1
/gps/particle electron
/gps/number 1
/gps/direction 0 0 0.423984
/gps/ene/mono 0.263461 MeV
/gps/position 0. 0. -208.15 m
/run/beamOn 1
/gps/particle electron
/gps/number 1
/gps/direction 0 0 0.356896
/gps/ene/mono 0.110117 MeV
/gps/position 0. 0. -156.746 m
/run/beamOn 1
/gps/particle electron
/gps/number 1
/gps/direction 0 0 0.415538
/gps/ene/mono 0.131419 MeV
/gps/position 0. 0. -148.606 m
/run/beamOn 1
/gps/particle electron
/gps/number 1
/gps/direction 0 0 0.50686
/gps/ene/mono 0.168848 MeV
/gps/position 0. 0. -77.5984 m
/run/beamOn 1
/gps/particle electron
/gps/number 1
/gps/direction 0 0 0.354913
/gps/ene/mono 0.119356 MeV
/gps/position 0. 0. -65.9751 m
/run/beamOn 1
/gps/particle electron
/gps/number 1
/gps/direction 0 0 0.444386
/gps/ene/mono 0.31778 MeV
/gps/position 0. 0. -56.9404 m
/run/beamOn 1
/gps/particle electron
/gps/number 1
/gps/direction 0 0 0.447694
/gps/ene/mono 0.374674 MeV
/gps/position 0. 0. -32.3106 m
/run/beamOn 1
/gps/particle electron
/gps/number 1
/gps/direction 0 0 0.587286
/gps/ene/mono 0.163756 MeV
/gps/position 0. 0. -26.4138 m
/run/beamOn 1
/gps/particle electron
/gps/number 1
/gps/direction 0 0 0.586403
/gps/ene/mono 0.112493 MeV
/gps/position 0. 0. 19.937 m
/run/beamOn 1
/gps/particle electron
/gps/number 1
/gps/direction 0 0 0.638197
/gps/ene/mono 0.141439 MeV
/gps/position 0. 0. 42.6498 m
/run/beamOn 1
/gps/particle electron
/gps/number 1
/gps/direction 0 0 0.619053
/gps/ene/mono 0.15765 MeV
/gps/position 0. 0. 69.0874 m
/run/beamOn 1
/gps/particle electron
/gps/number 1
/gps/direction 0 0 0.503458
/gps/ene/mono 0.889115 MeV
/gps/position 0. 0. 76.2851 m
/run/beamOn 1
/gps/particle electron
/gps/number 1
/gps/direction 0 0 0.297704
/gps/ene/mono 0.148292 MeV
/gps/position 0. 0. 98.5591 m
/run/beamOn 1
/gps/particle electron
/gps/number 1
/gps/direction 0 0 0.869338
/gps/ene/mono 2.53477 MeV
/gps/position 0. 0. 103.889 m
/run/beamOn 1
/gps/particle electron
/gps/number 1
/gps/direction 0 0 0.26328
/gps/ene/mono 0.149285 MeV
/gps/position 0. 0. 246.344 m
/run/beamOn 1
/gps/particle electron
/gps/number 1
/gps/direction 0 0 0.360311
/gps/ene/mono 0.107054 MeV
/gps/position 0. 0. 246.446 m
/run/beamOn 1
/gps/particle electron
/gps/number 1
/gps/direction 0 0 0.558779
/gps/ene/mono 0.290291 MeV
/gps/position 0. 0. 270.438 m
/run/beamOn 1
/gps/particle electron
/gps/number 1
/gps/direction 0 0 0.428703
/gps/ene/mono 0.181323 MeV
/gps/position 0. 0. 274.417 m
/run/beamOn 1
/gps/particle electron
/gps/number 1
/gps/direction 0 0 0.609726
/gps/ene/mono 0.945446 MeV
/gps/position 0. 0. 275.693 m
/run/beamOn 1
/gps/particle electron
/gps/number 1
/gps/direction 0 0 0.84786
/gps/ene/mono 0.321259 MeV
/gps/position 0. 0. 46.8052 m
/run/beamOn 1
/gps/particle electron
/gps/number 1
/gps/direction 0 0 0.902108
/gps/ene/mono 0.985766 MeV
/gps/position 0. 0. 49.158 m
/run/beamOn 1
/gps/particle electron
/gps/number 1
/gps/direction 0 0 0.760036
/gps/ene/mono 0.10694 MeV
/gps/position 0. 0. -189.579 m
/run/beamOn 1
/gps/particle electron
/gps/number 1
/gps/direction 0 0 0.184957
/gps/ene/mono 0.109802 MeV
/gps/position 0. 0. -122.257 m
/run/beamOn 1
/gps/particle electron
/gps/number 1
/gps/direction 0 0 0.0833032
/gps/ene/mono 0.104243 MeV
/gps/position 0. 0. -76.1415 m
/run/beamOn 1
/gps/particle electron
/gps/number 1
/gps/direction 0 0 0.597431
/gps/ene/mono 0.437623 MeV
/gps/position 0. 0. -55.8892 m
/run/beamOn 1
/gps/particle electron
/gps/number 1
/gps/direction 0 0 0.528173
/gps/ene/mono 0.164664 MeV
/gps/position 0. 0. -41.2059 m
/run/beamOn 1
/gps/particle electron
/gps/number 1
/gps/direction 0 0 0.396099
/gps/ene/mono 0.139556 MeV
/gps/position 0. 0. -39.7752 m
/run/beamOn 1
/gps/particle electron
/gps/number 1
/gps/direction 0 0 0.699113
/gps/ene/mono 1.25974 MeV
/gps/position 0. 0. 26.1982 m
/run/beamOn 1
/gps/particle electron
/gps/number 1
/gps/direction 0 0 0.713713
/gps/ene/mono 0.520122 MeV
/gps/position 0. 0. 27.6826 m
/run/beamOn 1
/gps/particle electron
/gps/number 1
/gps/direction 0 0 0.23532
/gps/ene/mono 0.133764 MeV
/gps/position 0. 0. 75.6838 m
/run/beamOn 1
/gps/particle electron
/gps/number 1
/gps/direction 0 0 0.270022
/gps/ene/mono 0.126403 MeV
/gps/position 0. 0. 138.197 m
/run/beamOn 1
/gps/particle electron
/gps/number 1
/gps/direction 0 0 0.47384
/gps/ene/mono 0.240046 MeV
/gps/position 0. 0. 173.341 m
/run/beamOn 1
/gps/particle electron
/gps/number 1
/gps/direction 0 0 0.534875
/gps/ene/mono 0.114565 MeV
/gps/position 0. 0. 219.933 m
/run/beamOn 1
/gps/particle electron
/gps/number 1
/gps/direction 0 0 0.218131
/gps/ene/mono 0.130437 MeV
/gps/position 0. 0. 238.145 m
/run/beamOn 1
/gps/particle electron
/gps/number 1
/gps/direction 0 0 0.427249
/gps/ene/mono 0.198679 MeV
/gps/position 0. 0. 262.826 m
/run/beamOn 1
/gps/particle electron
/gps/number 1
/gps/direction 0 0 0.881471
/gps/ene/mono 2.72854 MeV
/gps/position 0. 0. 319.659 m
/run/beamOn 1
/gps/particle electron
/gps/number 1
/gps/direction 0 0 0.19844
/gps/ene/mono 0.220228 MeV
/gps/position 0. 0. 338.781 m
/run/beamOn 1
/gps/particle electron
/gps/number 1
/gps/direction 0 0 0.936228
/gps/ene/mono 0.612112 MeV
/gps/position 0. 0. 163.857 m
/run/beamOn 1
/gps/particle electron
/gps/number 1
/gps/direction 0 0 0.869086
/gps/ene/mono 0.273683 MeV
/gps/position 0. 0. 56.3469 m
/run/beamOn 1
/gps/particle electron
/gps/number 1
/gps/direction 0 0 0.392333
/gps/ene/mono 0.215817 MeV
/gps/position 0. 0. -247.672 m
/run/beamOn 1
/gps/particle electron
/gps/number 1
/gps/direction 0 0 0.014652
/gps/ene/mono 0.180049 MeV
/gps/position 0. 0. -209.15 m
/run/beamOn 1
/gps/particle electron
/gps/number 1
/gps/direction 0 0 0.52718
/gps/ene/mono 0.492455 MeV
/gps/position 0. 0. -207.291 m
/run/beamOn 1
/gps/particle electron
/gps/number 1
/gps/direction 0 0 0.22291
/gps/ene/mono 0.312011 MeV
/gps/position 0. 0. -187.638 m
/run/beamOn 1
/gps/particle electron
/gps/number 1
/gps/direction 0 0 0.876024
/gps/ene/mono 3.44085 MeV
/gps/position 0. 0. -145.06 m
/run/beamOn 1
/gps/particle electron
/gps/number 1
/gps/direction 0 0 0.383175
/gps/ene/mono 0.186652 MeV
/gps/position 0. 0. -127.831 m
/run/beamOn 1
/gps/particle electron
/gps/number 1
/gps/direction 0 0 0.728303
/gps/ene/mono 0.448502 MeV
/gps/position 0. 0. -102.996 m
/run/beamOn 1
/gps/particle electron
/gps/number 1
/gps/direction 0 0 0.563194
/gps/ene/mono 0.115251 MeV
/gps/position 0. 0. -41.0673 m
/run/beamOn 1
/gps/particle electron
/gps/number 1
/gps/direction 0 0 0.168629
/gps/ene/mono 0.150172 MeV
/gps/position 0. 0. -27.045 m
/run/beamOn 1
/gps/particle electron
/gps/number 1
/gps/direction 0 0 0.104874
/gps/ene/mono 0.108338 MeV
/gps/position 0. 0. -14.6411 m
/run/beamOn 1
/gps/particle electron
/gps/number 1
/gps/direction 0 0 0.79068
/gps/ene/mono 0.258213 MeV
/gps/position 0. 0. 5.69879 m
/run/beamOn 1
/gps/particle electron
/gps/number 1
/gps/direction 0 0 0.0782766
/gps/ene/mono 0.112482 MeV
/gps/position 0. 0. 16.091 m
/run/beamOn 1
/gps/particle electron
/gps/number 1
/gps/direction 0 0 0.0844853
/gps/ene/mono 0.135653 MeV
/gps/position 0. 0. 19.1766 m
/run/beamOn 1
/gps/particle electron
/gps/number 1
/gps/direction 0 0 -0.00252706
/gps/ene/mono 0.169557 MeV
/gps/position 0. 0. 25.1199 m
/run/beamOn 1
/gps/particle electron
/gps/number 1
/gps/direction 0 0 0.689946
/gps/ene/mono 0.442241 MeV
/gps/position 0. 0. 67.2875 m
/run/beamOn 1
/gps/particle electron
/gps/number 1
/gps/direction 0 0 0.498656
/gps/ene/mono 0.270724 MeV
/gps/position 0. 0. 71.9592 m
/run/beamOn 1
/gps/particle electron
/gps/number 1
/gps/direction 0 0 0.532415
/gps/ene/mono 0.172795 MeV
/gps/position 0. 0. 120.044 m
/run/beamOn 1
/gps/particle electron
/gps/number 1
/gps/direction 0 0 0.387672
/gps/ene/mono 0.24274 MeV
/gps/position 0. 0. 125.594 m
/run/beamOn 1
/gps/particle electron
/gps/number 1
/gps/direction 0 0 0.582467
/gps/ene/mono 0.116725 MeV
/gps/position 0. 0. 157.878 m
/run/beamOn 1
/gps/particle electron
/gps/number 1
/gps/direction 0 0 0.739664
/gps/ene/mono 0.99842 MeV
/gps/position 0. 0. 207.866 m
/run/beamOn 1
/gps/particle electron
/gps/number 1
/gps/direction 0 0 0.258001
/gps/ene/mono 0.28185 MeV
/gps/position 0. 0. 222.66 m
/run/beamOn 1
/gps/particle electron
/gps/number 1
/gps/direction 0 0 -0.00163483
/gps/ene/mono 0.127919 MeV
/gps/position 0. 0. 225.465 m
/run/beamOn 1
/gps/particle electron
/gps/number 1
/gps/direction 0 0 0.461451
/gps/ene/mono 0.112484 MeV
/gps/position 0. 0. 238.141 m
/run/beamOn 1
/gps/particle electron
/gps/number 1
/gps/direction 0 0 0.611717
/gps/ene/mono 1.53379 MeV
/gps/position 0. 0. 249.819 m
/run/beamOn 1
/gps/particle electron
/gps/number 1
/gps/direction 0 0 0.391186
/gps/ene/mono 0.109649 MeV
/gps/position 0. 0. 327.631 m
/run/beamOn 1
/gps/particle electron
/gps/number 1
/gps/direction 0 0 0.919404
/gps/ene/mono 0.116883 MeV
/gps/position 0. 0. -78.5531 m
/run/beamOn 1
/gps/particle electron
/gps/number 1
/gps/direction 0 0 0.891772
/gps/ene/mono 1.06048 MeV
/gps/position 0. 0. -107.782 m
/run/beamOn 1
/gps/particle electron
/gps/number 1
/gps/direction 0 0 0.527935
/gps/ene/mono 0.107369 MeV
/gps/position 0. 0. -73.3314 m
/run/beamOn 1
/gps/particle electron
/gps/number 1
/gps/direction 0 0 0.383654
/gps/ene/mono 0.146373 MeV
/gps/position 0. 0. -293.791 m
/run/beamOn 1
/gps/particle electron
/gps/number 1
/gps/direction 0 0 0.0546244
/gps/ene/mono 0.443124 MeV
/gps/position 0. 0. -271.673 m
/run/beamOn 1
/gps/particle electron
/gps/number 1
/gps/direction 0 0 0.703869
/gps/ene/mono 3.5273 MeV
/gps/position 0. 0. -268.735 m
/run/beamOn 1
/gps/particle electron
/gps/number 1
/gps/direction 0 0 0.343611
/gps/ene/mono 0.223565 MeV
/gps/position 0. 0. -240.825 m
/run/beamOn 1
/gps/particle electron
/gps/number 1
/gps/direction 0 0 0.519489
/gps/ene/mono 0.475645 MeV
/gps/position 0. 0. -192.203 m
/run/beamOn 1
/gps/particle electron
/gps/number 1
/gps/direction 0 0 0.313687
/gps/ene/mono 0.119421 MeV
/gps/position 0. 0. -187.743 m
/run/beamOn 1
/gps/particle electron
/gps/number 1
/gps/direction 0 0 0.662607
/gps/ene/mono 0.148582 MeV
/gps/position 0. 0. -182.968 m
/run/beamOn 1
/gps/particle electron
/gps/number 1
/gps/direction 0 0 0.447179
/gps/ene/mono 0.252593 MeV
/gps/position 0. 0. -142.731 m
/run/beamOn 1
/gps/particle electron
/gps/number 1
/gps/direction 0 0 0.813872
/gps/ene/mono 1.01325 MeV
/gps/position 0. 0. -129.52 m
/run/beamOn 1
/gps/particle electron
/gps/number 1
/gps/direction 0 0 -0.00835634
/gps/ene/mono 0.104674 MeV
/gps/position 0. 0. -128.968 m
/run/beamOn 1
/gps/particle electron
/gps/number 1
/gps/direction 0 0 0.203403
/gps/ene/mono 0.121864 MeV
/gps/position 0. 0. -104.627 m
/run/beamOn 1
/gps/particle electron
/gps/number 1
/gps/direction 0 0 0.541156
/gps/ene/mono 0.285006 MeV
/gps/position 0. 0. -102.485 m
/run/beamOn 1
/gps/particle electron
/gps/number 1
/gps/direction 0 0 0.404181
/gps/ene/mono 0.118102 MeV
/gps/position 0. 0. -26.8774 m
/run/beamOn 1
/gps/particle electron
/gps/number 1
/gps/direction 0 0 0.517828
/gps/ene/mono 0.25094 MeV
/gps/position 0. 0. -22.4729 m
/run/beamOn 1
/gps/particle electron
/gps/number 1
/gps/direction 0 0 0.373233
/gps/ene/mono 0.207501 MeV
/gps/position 0. 0. 10.9939 m
/run/beamOn 1
/gps/particle electron
/gps/number 1
/gps/direction 0 0 0.544368
/gps/ene/mono 0.182872 MeV
/gps/position 0. 0. 54.3463 m
/run/beamOn 1
/gps/particle electron
/gps/number 1
/gps/direction 0 0 0.418348
/gps/ene/mono 0.136463 MeV
/gps/position 0. 0. 94.8733 m
/run/beamOn 1
/gps/particle electron
/gps/number 1
/gps/direction 0 0 0.456366
/gps/ene/mono 0.115258 MeV
/gps/position 0. 0. 95.1313 m
/run/beamOn 1
/gps/particle electron
/gps/number 1
/gps/direction 0 0 0.392669
/gps/ene/mono 0.460841 MeV
/gps/position 0. 0. 99.2934 m
/run/beamOn 1
/gps/particle electron
/gps/number 1
/gps/direction 0 0 0.69914
/gps/ene/mono 0.64242 MeV
/gps/position 0. 0. 107.666 m
/run/beamOn 1
/gps/particle electron
/gps/number 1
/gps/direction 0 0 0.30511
/gps/ene/mono 0.120913 MeV
/gps/position 0. 0. 110.592 m
/run/beamOn 1
/gps/particle electron
/gps/number 1
/gps/direction 0 0 0.293139
/gps/ene/mono 0.134614 MeV
/gps/position 0. 0. 117.8 m
/run/beamOn 1
/gps/particle electron
/gps/number 1
/gps/direction 0 0 0.543538
/gps/ene/mono 0.122048 MeV
/gps/position 0. 0. 153.734 m
/run/beamOn 1
/gps/particle electron
/gps/number 1
/gps/direction 0 0 0.55694
/gps/ene/mono 0.573552 MeV
/gps/position 0. 0. 195.241 m
/run/beamOn 1
/gps/particle electron
/gps/number 1
/gps/direction 0 0 0.482404
/gps/ene/mono 0.508379 MeV
/gps/position 0. 0. 225.137 m
/run/beamOn 1
/gps/particle electron
/gps/number 1
/gps/direction 0 0 0.453344
/gps/ene/mono 0.221979 MeV
/gps/position 0. 0. 239.948 m
/run/beamOn 1
/gps/particle electron
/gps/number 1
/gps/direction 0 0 0.500373
/gps/ene/mono 0.140071 MeV
/gps/position 0. 0. 328.783 m
/run/beamOn 1
/gps/particle electron
/gps/number 1
/gps/direction 0 0 0.894711
/gps/ene/mono 1.06619 MeV
/gps/position 0. 0. 60.1787 m
/run/beamOn 1
/gps/particle electron
/gps/number 1
/gps/direction 0 0 -0.455467
/gps/ene/mono 0.106055 MeV
/gps/position 0. 0. -264.076 m
/run/beamOn 1
/gps/particle electron
/gps/number 1
/gps/direction 0 0 -0.333675
/gps/ene/mono 0.220559 MeV
/gps/position 0. 0. -276.629 m
/run/beamOn 1
/gps/particle electron
/gps/number 1
/gps/direction 0 0 -0.667025
/gps/ene/mono 0.105016 MeV
/gps/position 0. 0. -164.572 m
/run/beamOn 1
/gps/particle electron
/gps/number 1
/gps/direction 0 0 0.608509
/gps/ene/mono 0.272274 MeV
/gps/position 0. 0. -84.9226 m
/run/beamOn 1
/gps/particle electron
/gps/number 1
/gps/direction 0 0 0.887987
/gps/ene/mono 0.337387 MeV
/gps/position 0. 0. -38.2884 m
/run/beamOn 1
/gps/particle electron
/gps/number 1
/gps/direction 0 0 0.22957
/gps/ene/mono 0.137478 MeV
/gps/position 0. 0. -193.216 m
/run/beamOn 1
/gps/particle electron
/gps/number 1
/gps/direction 0 0 0.667161
/gps/ene/mono 0.203764 MeV
/gps/position 0. 0. -159.109 m
/run/beamOn 1
/gps/particle electron
/gps/number 1
/gps/direction 0 0 -0.769008
/gps/ene/mono 0.723286 MeV
/gps/position 0. 0. -319.978 m
/run/beamOn 1
/gps/particle electron
/gps/number 1
/gps/direction 0 0 0.48228
/gps/ene/mono 0.421866 MeV
/gps/position 0. 0. -332.036 m
/run/beamOn 1
/gps/particle electron
/gps/number 1
/gps/direction 0 0 0.194749
/gps/ene/mono 0.114694 MeV
/gps/position 0. 0. -300.618 m
/run/beamOn 1
/gps/particle electron
/gps/number 1
/gps/direction 0 0 0.570546
/gps/ene/mono 0.211053 MeV
/gps/position 0. 0. -293.266 m
/run/beamOn 1
/gps/particle electron
/gps/number 1
/gps/direction 0 0 0.417888
/gps/ene/mono 0.31176 MeV
/gps/position 0. 0. -261.559 m
/run/beamOn 1
/gps/particle electron
/gps/number 1
/gps/direction 0 0 0.615289
/gps/ene/mono 0.113314 MeV
/gps/position 0. 0. -246.444 m
/run/beamOn 1
/gps/particle electron
/gps/number 1
/gps/direction 0 0 0.241465
/gps/ene/mono 0.270905 MeV
/gps/position 0. 0. -227.617 m
/run/beamOn 1
/gps/particle electron
/gps/number 1
/gps/direction 0 0 0.603115
/gps/ene/mono 0.30258 MeV
/gps/position 0. 0. -97.1312 m
/run/beamOn 1
/gps/particle electron
/gps/number 1
/gps/direction 0 0 0.308016
/gps/ene/mono 0.292317 MeV
/gps/position 0. 0. -65.9499 m
/run/beamOn 1
/gps/particle electron
/gps/number 1
/gps/direction 0 0 0.292495
/gps/ene/mono 0.12006 MeV
/gps/position 0. 0. 32.5055 m
/run/beamOn 1
/gps/particle electron
/gps/number 1
/gps/direction 0 0 0.75665
/gps/ene/mono 0.461035 MeV
/gps/position 0. 0. 44.4598 m
/run/beamOn 1
/gps/particle electron
/gps/number 1
/gps/direction 0 0 0.549231
/gps/ene/mono 0.167914 MeV
/gps/position 0. 0. 125.705 m
/run/beamOn 1
/gps/particle electron
/gps/number 1
/gps/direction 0 0 0.247967
/gps/ene/mono 0.132696 MeV
/gps/position 0. 0. 132.359 m
/run/beamOn 1
/gps/particle electron
/gps/number 1
/gps/direction 0 0 0.925704
/gps/ene/mono 11.8693 MeV
/gps/position 0. 0. 136.292 m
/run/beamOn 1
/gps/particle electron
/gps/number 1
/gps/direction 0 0 0.309711
/gps/ene/mono 0.108251 MeV
/gps/position 0. 0. 143.855 m
/run/beamOn 1
/gps/particle electron
/gps/number 1
/gps/direction 0 0 0.242582
/gps/ene/mono 0.112699 MeV
/gps/position 0. 0. 161.59 m
/run/beamOn 1
/gps/particle electron
/gps/number 1
/gps/direction 0 0 0.207597
/gps/ene/mono 0.112455 MeV
/gps/position 0. 0. 174.072 m
/run/beamOn 1
/gps/particle electron
/gps/number 1
/gps/direction 0 0 0.444324
/gps/ene/mono 0.167575 MeV
/gps/position 0. 0. 189.564 m
/run/beamOn 1
/gps/particle electron
/gps/number 1
/gps/direction 0 0 0.453406
/gps/ene/mono 0.334751 MeV
/gps/position 0. 0. 198.762 m
/run/beamOn 1
/gps/particle electron
/gps/number 1
/gps/direction 0 0 0.423048
/gps/ene/mono 0.143112 MeV
/gps/position 0. 0. 200.959 m
/run/beamOn 1
/gps/particle electron
/gps/number 1
/gps/direction 0 0 0.301452
/gps/ene/mono 0.138115 MeV
/gps/position 0. 0. 222.008 m
/run/beamOn 1
/gps/particle electron
/gps/number 1
/gps/direction 0 0 0.283078
/gps/ene/mono 0.102521 MeV
/gps/position 0. 0. 253.457 m
/run/beamOn 1
/gps/particle electron
/gps/number 1
/gps/direction 0 0 0.52191
/gps/ene/mono 0.472811 MeV
/gps/position 0. 0. 254.105 m
/run/beamOn 1
/gps/particle electron
/gps/number 1
/gps/direction 0 0 0.552664
/gps/ene/mono 0.378127 MeV
/gps/position 0. 0. 267.918 m
/run/beamOn 1
/gps/particle electron
/gps/number 1
/gps/direction 0 0 0.918213
/gps/ene/mono 3.66171 MeV
/gps/position 0. 0. 276.848 m
/run/beamOn 1
/gps/particle electron
/gps/number 1
/gps/direction 0 0 0.749019
/gps/ene/mono 1.27827 MeV
/gps/position 0. 0. 310.412 m
/run/beamOn 1
/gps/particle electron
/gps/number 1
/gps/direction 0 0 0.111876
/gps/ene/mono 0.339221 MeV
/gps/position 0. 0. -279.179 m
/run/beamOn 1
/gps/particle electron
/gps/number 1
/gps/direction 0 0 -0.177855
/gps/ene/mono 0.333988 MeV
/gps/position 0. 0. -290.067 m
/run/beamOn 1
/gps/particle electron
/gps/number 1
/gps/direction 0 0 -0.138142
/gps/ene/mono 0.124206 MeV
/gps/position 0. 0. -227.956 m
/run/beamOn 1
/gps/particle electron
/gps/number 1
/gps/direction 0 0 0.189527
/gps/ene/mono 0.192756 MeV
/gps/position 0. 0. -226.026 m
/run/beamOn 1
/gps/particle electron
/gps/number 1
/gps/direction 0 0 0.262159
/gps/ene/mono 0.237816 MeV
/gps/position 0. 0. -184.757 m
/run/beamOn 1
/gps/particle electron
/gps/number 1
/gps/direction 0 0 0.490866
/gps/ene/mono 0.270746 MeV
/gps/position 0. 0. -174.271 m
/run/beamOn 1
/gps/particle electron
/gps/number 1
/gps/direction 0 0 0.595415
/gps/ene/mono 0.315197 MeV
/gps/position 0. 0. -108.048 m
/run/beamOn 1
/gps/particle electron
/gps/number 1
/gps/direction 0 0 0.628447
/gps/ene/mono 0.308186 MeV
/gps/position 0. 0. -85.3048 m
/run/beamOn 1
/gps/particle electron
/gps/number 1
/gps/direction 0 0 0.393458
/gps/ene/mono 0.109097 MeV
/gps/position 0. 0. -51.7721 m
/run/beamOn 1
/gps/particle electron
/gps/number 1
/gps/direction 0 0 0.38298
/gps/ene/mono 0.138286 MeV
/gps/position 0. 0. 31.0498 m
/run/beamOn 1
/gps/particle electron
/gps/number 1
/gps/direction 0 0 0.512069
/gps/ene/mono 0.438301 MeV
/gps/position 0. 0. 34.2687 m
/run/beamOn 1
/gps/particle electron
/gps/number 1
/gps/direction 0 0 0.473262
/gps/ene/mono 0.276522 MeV
/gps/position 0. 0. 50.2418 m
/run/beamOn 1
/gps/particle electron
/gps/number 1
/gps/direction 0 0 0.382565
/gps/ene/mono 0.123879 MeV
/gps/position 0. 0. 82.6718 m
/run/beamOn 1
/gps/particle electron
/gps/number 1
/gps/direction 0 0 0.278199
/gps/ene/mono 0.145097 MeV
/gps/position 0. 0. 97.5603 m
/run/beamOn 1
/gps/particle electron
/gps/number 1
/gps/direction 0 0 0.462415
/gps/ene/mono 0.264516 MeV
/gps/position 0. 0. 98.9804 m
/run/beamOn 1
/gps/particle electron
/gps/number 1
/gps/direction 0 0 0.243664
/gps/ene/mono 0.123524 MeV
/gps/position 0. 0. 143.33 m
/run/beamOn 1
/gps/particle electron
/gps/number 1
/gps/direction 0 0 0.727811
/gps/ene/mono 0.543608 MeV
/gps/position 0. 0. 160.776 m
/run/beamOn 1
/gps/particle electron
/gps/number 1
/gps/direction 0 0 0.118745
/gps/ene/mono 0.120143 MeV
/gps/position 0. 0. 177.379 m
/run/beamOn 1
/gps/particle electron
/gps/number 1
/gps/direction 0 0 0.130568
/gps/ene/mono 0.118008 MeV
/gps/position 0. 0. 212.056 m
/run/beamOn 1
/gps/particle electron
/gps/number 1
/gps/direction 0 0 0.45104
/gps/ene/mono 0.16395 MeV
/gps/position 0. 0. 227.384 m
/run/beamOn 1
/gps/particle electron
/gps/number 1
/gps/direction 0 0 0.214893
/gps/ene/mono 0.114246 MeV
/gps/position 0. 0. 254.282 m
/run/beamOn 1
/gps/particle electron
/gps/number 1
/gps/direction 0 0 0.93391
/gps/ene/mono 4.64375 MeV
/gps/position 0. 0. 263.409 m
/run/beamOn 1
/gps/particle electron
/gps/number 1
/gps/direction 0 0 0.263058
/gps/ene/mono 0.152795 MeV
/gps/position 0. 0. 277.166 m
/run/beamOn 1
/gps/particle electron
/gps/number 1
/gps/direction 0 0 0.367901
/gps/ene/mono 0.12868 MeV
/gps/position 0. 0. 316.406 m
/run/beamOn 1
/gps/particle electron
/gps/number 1
/gps/direction 0 0 0.304173
/gps/ene/mono 0.123275 MeV
/gps/position 0. 0. 344.535 m
/run/beamOn 1
/gps/particle electron
/gps/number 1
/gps/direction 0 0 0.732764
/gps/ene/mono 0.511637 MeV
/gps/position 0. 0. 258.606 m
/run/beamOn 1
/gps/particle electron
/gps/number 1
/gps/direction 0 0 0.834908
/gps/ene/mono 1.84422 MeV
/gps/position 0. 0. -293.148 m
/run/beamOn 1
/gps/particle electron
/gps/number 1
/gps/direction 0 0 0.448571
/gps/ene/mono 0.102321 MeV
/gps/position 0. 0. -134.218 m
/run/beamOn 1
/gps/particle electron
/gps/number 1
/gps/direction 0 0 0.332009
/gps/ene/mono 0.198054 MeV
/gps/position 0. 0. -113.119 m
/run/beamOn 1
/gps/particle electron
/gps/number 1
/gps/direction 0 0 0.558592
/gps/ene/mono 0.347786 MeV
/gps/position 0. 0. -104.244 m
/run/beamOn 1
/gps/particle electron
/gps/number 1
/gps/direction 0 0 0.472613
/gps/ene/mono 0.219297 MeV
/gps/position 0. 0. 41.6459 m
/run/beamOn 1
/gps/particle electron
/gps/number 1
/gps/direction 0 0 0.10143
/gps/ene/mono 0.117003 MeV
/gps/position 0. 0. 134.525 m
/run/beamOn 1
/gps/particle electron
/gps/number 1
/gps/direction 0 0 0.220623
/gps/ene/mono 0.132667 MeV
/gps/position 0. 0. 198.556 m
/run/beamOn 1
/gps/particle electron
/gps/number 1
/gps/direction 0 0 0.716176
/gps/ene/mono 1.64684 MeV
/gps/position 0. 0. 199.957 m
/run/beamOn 1
/gps/particle electron
/gps/number 1
/gps/direction 0 0 0.49653
/gps/ene/mono 0.113612 MeV
/gps/position 0. 0. 263.363 m
/run/beamOn 1
/gps/particle electron
/gps/number 1
/gps/direction 0 0 0.397899
/gps/ene/mono 0.291938 MeV
/gps/position 0. 0. 278.316 m
/run/beamOn 1
/gps/particle electron
/gps/number 1
/gps/direction 0 0 0.237794
/gps/ene/mono 0.226975 MeV
/gps/position 0. 0. 283.111 m
/run/beamOn 1
/gps/particle electron
/gps/number 1
/gps/direction 0 0 0.273194
/gps/ene/mono 0.241559 MeV
/gps/position 0. 0. 296.732 m
/run/beamOn 1
/gps/particle electron
/gps/number 1
/gps/direction 0 0 0.697985
/gps/ene/mono 0.594963 MeV
/gps/position 0. 0. 322.957 m
/run/beamOn 1
/gps/particle electron
/gps/number 1
/gps/direction 0 0 0.894989
/gps/ene/mono 0.207267 MeV
/gps/position 0. 0. -147.714 m
/run/beamOn 1
/gps/particle electron
/gps/number 1
/gps/direction 0 0 0.765946
/gps/ene/mono 0.113158 MeV
/gps/position 0. 0. -317.027 m
/run/beamOn 1
/gps/particle electron
/gps/number 1
/gps/direction 0 0 0.0268861
/gps/ene/mono 0.260047 MeV
/gps/position 0. 0. -331.45 m
/run/beamOn 1
/gps/particle electron
/gps/number 1
/gps/direction 0 0 0.324046
/gps/ene/mono 0.108933 MeV
/gps/position 0. 0. -323.716 m
/run/beamOn 1
/gps/particle electron
/gps/number 1
/gps/direction 0 0 0.264239
/gps/ene/mono 0.601388 MeV
/gps/position 0. 0. -197.904 m
/run/beamOn 1
/gps/particle electron
/gps/number 1
/gps/direction 0 0 0.496331
/gps/ene/mono 0.315806 MeV
/gps/position 0. 0. -138.216 m
/run/beamOn 1
/gps/particle electron
/gps/number 1
/gps/direction 0 0 0.487003
/gps/ene/mono 0.328171 MeV
/gps/position 0. 0. -101.063 m
/run/beamOn 1
/gps/particle electron
/gps/number 1
/gps/direction 0 0 0.672172
/gps/ene/mono 0.633261 MeV
/gps/position 0. 0. -92.798 m
/run/beamOn 1
/gps/particle electron
/gps/number 1
/gps/direction 0 0 0.584263
/gps/ene/mono 0.987954 MeV
/gps/position 0. 0. -85.9354 m
/run/beamOn 1
/gps/particle electron
/gps/number 1
/gps/direction 0 0 0.367452
/gps/ene/mono 0.230377 MeV
/gps/position 0. 0. -49.0563 m
/run/beamOn 1
/gps/particle electron
/gps/number 1
/gps/direction 0 0 0.266291
/gps/ene/mono 0.19032 MeV
/gps/position 0. 0. -26.5982 m
/run/beamOn 1
/gps/particle electron
/gps/number 1
/gps/direction 0 0 0.514886
/gps/ene/mono 0.627306 MeV
/gps/position 0. 0. -20.4381 m
/run/beamOn 1
/gps/particle electron
/gps/number 1
/gps/direction 0 0 0.684904
/gps/ene/mono 0.158807 MeV
/gps/position 0. 0. 44.5883 m
/run/beamOn 1
/gps/particle electron
/gps/number 1
/gps/direction 0 0 0.0645724
/gps/ene/mono 0.172582 MeV
/gps/position 0. 0. 41.3631 m
/run/beamOn 1
/gps/particle electron
/gps/number 1
/gps/direction 0 0 -0.414036
/gps/ene/mono 0.637057 MeV
/gps/position 0. 0. 40.4323 m
/run/beamOn 1
/gps/particle electron
/gps/number 1
/gps/direction 0 0 0.458179
/gps/ene/mono 0.115444 MeV
/gps/position 0. 0. 79.3276 m
/run/beamOn 1
/gps/particle electron
/gps/number 1
/gps/direction 0 0 0.072347
/gps/ene/mono 0.239902 MeV
/gps/position 0. 0. 128.932 m
/run/beamOn 1
/gps/particle electron
/gps/number 1
/gps/direction 0 0 0.508763
/gps/ene/mono 0.124901 MeV
/gps/position 0. 0. 159.253 m
/run/beamOn 1
/gps/particle electron
/gps/number 1
/gps/direction 0 0 0.0763938
/gps/ene/mono 0.115867 MeV
/gps/position 0. 0. 164.17 m
/run/beamOn 1
/gps/particle electron
/gps/number 1
/gps/direction 0 0 0.743313
/gps/ene/mono 1.06031 MeV
/gps/position 0. 0. 241.519 m
/run/beamOn 1
/gps/particle electron
/gps/number 1
/gps/direction 0 0 0.384398
/gps/ene/mono 0.19818 MeV
/gps/position 0. 0. 290.159 m
/run/beamOn 1
/gps/particle electron
/gps/number 1
/gps/direction 0 0 0.313133
/gps/ene/mono 0.102442 MeV
/gps/position 0. 0. 310.621 m
/run/beamOn 1
/gps/particle electron
/gps/number 1
/gps/direction 0 0 0.567335
/gps/ene/mono 10.5003 MeV
/gps/position 0. 0. 123.85 m
/run/beamOn 1
/gps/particle electron
/gps/number 1
/gps/direction 0 0 -0.0462814
/gps/ene/mono 0.421158 MeV
/gps/position 0. 0. 52.875 m
/run/beamOn 1
/gps/particle electron
/gps/number 1
/gps/direction 0 0 0.988776
/gps/ene/mono 0.626108 MeV
/gps/position 0. 0. 104.828 m
/run/beamOn 1
/gps/particle electron
/gps/number 1
/gps/direction 0 0 0.900738
/gps/ene/mono 0.658333 MeV
/gps/position 0. 0. 128.659 m
/run/beamOn 1
/gps/particle electron
/gps/number 1
/gps/direction 0 0 0.683717
/gps/ene/mono 0.306524 MeV
/gps/position 0. 0. -319.054 m
/run/beamOn 1
/gps/particle electron
/gps/number 1
/gps/direction 0 0 0.296039
/gps/ene/mono 0.113642 MeV
/gps/position 0. 0. -301.269 m
/run/beamOn 1
/gps/particle electron
/gps/number 1
/gps/direction 0 0 0.0891772
/gps/ene/mono 0.139709 MeV
/gps/position 0. 0. -249.622 m
/run/beamOn 1
/gps/particle electron
/gps/number 1
/gps/direction 0 0 0.550232
/gps/ene/mono 0.156689 MeV
/gps/position 0. 0. -232.783 m
/run/beamOn 1
/gps/particle electron
/gps/number 1
/gps/direction 0 0 0.690245
/gps/ene/mono 0.32246 MeV
/gps/position 0. 0. -231.948 m
/run/beamOn 1
/gps/particle electron
/gps/number 1
/gps/direction 0 0 0.277402
/gps/ene/mono 0.261711 MeV
/gps/position 0. 0. -227.852 m
/run/beamOn 1
/gps/particle electron
/gps/number 1
/gps/direction 0 0 0.368574
/gps/ene/mono 0.149725 MeV
/gps/position 0. 0. -177.183 m
/run/beamOn 1
/gps/particle electron
/gps/number 1
/gps/direction 0 0 0.405787
/gps/ene/mono 0.595972 MeV
/gps/position 0. 0. -162.685 m
/run/beamOn 1
/gps/particle electron
/gps/number 1
/gps/direction 0 0 0.488785
/gps/ene/mono 0.142966 MeV
/gps/position 0. 0. -111.21 m
/run/beamOn 1
/gps/particle electron
/gps/number 1
/gps/direction 0 0 0.0698134
/gps/ene/mono 0.15857 MeV
/gps/position 0. 0. -93.8619 m
/run/beamOn 1
/gps/particle electron
/gps/number 1
/gps/direction 0 0 0.33223
/gps/ene/mono 0.41276 MeV
/gps/position 0. 0. -75.9684 m
/run/beamOn 1
/gps/particle electron
/gps/number 1
/gps/direction 0 0 0.488019
/gps/ene/mono 0.190106 MeV
/gps/position 0. 0. -75.0881 m
/run/beamOn 1
/gps/particle electron
/gps/number 1
/gps/direction 0 0 0.190035
/gps/ene/mono 0.100898 MeV
/gps/position 0. 0. -16.8844 m
/run/beamOn 1
/gps/particle electron
/gps/number 1
/gps/direction 0 0 0.766003
/gps/ene/mono 1.97183 MeV
/gps/position 0. 0. 101.015 m
/run/beamOn 1
/gps/particle electron
/gps/number 1
/gps/direction 0 0 0.311107
/gps/ene/mono 0.191689 MeV
/gps/position 0. 0. 103.183 m
/run/beamOn 1
/gps/particle electron
/gps/number 1
/gps/direction 0 0 0.506978
/gps/ene/mono 0.346366 MeV
/gps/position 0. 0. 110.535 m
/run/beamOn 1
/gps/particle electron
/gps/number 1
/gps/direction 0 0 0.467292
/gps/ene/mono 0.434788 MeV
/gps/position 0. 0. 122.437 m
/run/beamOn 1
/gps/particle electron
/gps/number 1
/gps/direction 0 0 0.537436
/gps/ene/mono 0.330027 MeV
/gps/position 0. 0. 150.31 m
/run/beamOn 1
/gps/particle electron
/gps/number 1
/gps/direction 0 0 0.696618
/gps/ene/mono 1.21128 MeV
/gps/position 0. 0. 201.046 m
/run/beamOn 1
/gps/particle electron
/gps/number 1
/gps/direction 0 0 0.558501
/gps/ene/mono 0.49827 MeV
/gps/position 0. 0. 267.473 m
/run/beamOn 1
/gps/particle electron
/gps/number 1
/gps/direction 0 0 0.986297
/gps/ene/mono 4.31845 MeV
/gps/position 0. 0. 241.987 m
/run/beamOn 1
/gps/particle electron
/gps/number 1
/gps/direction 0 0 0.592041
/gps/ene/mono 0.191977 MeV
/gps/position 0. 0. -11.0358 m
/run/beamOn 1
/gps/particle electron
/gps/number 1
/gps/direction 0 0 0.680272
/gps/ene/mono 0.211638 MeV
/gps/position 0. 0. 282.358 m
/run/beamOn 1
/gps/particle electron
/gps/number 1
/gps/direction 0 0 0.878922
/gps/ene/mono 0.10846 MeV
/gps/position 0. 0. -51.5926 m
/run/beamOn 1
/gps/particle electron
/gps/number 1
/gps/direction 0 0 0.94632
/gps/ene/mono 0.196881 MeV
/gps/position 0. 0. -289.362 m
/run/beamOn 1
/gps/particle electron
/gps/number 1
/gps/direction 0 0 -0.349475
/gps/ene/mono 0.189743 MeV
/gps/position 0. 0. -223.659 m
/run/beamOn 1
/gps/particle electron
/gps/number 1
/gps/direction 0 0 -0.662179
/gps/ene/mono 0.867787 MeV
/gps/position 0. 0. -227.179 m
/run/beamOn 1
/gps/particle electron
/gps/number 1
/gps/direction 0 0 0.597956
/gps/ene/mono 0.583137 MeV
/gps/position 0. 0. -195.281 m
/run/beamOn 1
/gps/particle electron
/gps/number 1
/gps/direction 0 0 0.788141
/gps/ene/mono 0.786986 MeV
/gps/position 0. 0. -184.435 m
/run/beamOn 1
/gps/particle electron
/gps/number 1
/gps/direction 0 0 0.428669
/gps/ene/mono 0.112821 MeV
/gps/position 0. 0. -129.129 m
/run/beamOn 1
/gps/particle electron
/gps/number 1
/gps/direction 0 0 0.0902931
/gps/ene/mono 0.125637 MeV
/gps/position 0. 0. -108.127 m
/run/beamOn 1
/gps/particle electron
/gps/number 1
/gps/direction 0 0 0.581133
/gps/ene/mono 0.527328 MeV
/gps/position 0. 0. -96.4817 m
/run/beamOn 1
/gps/particle electron
/gps/number 1
/gps/direction 0 0 0.847362
/gps/ene/mono 1.3714 MeV
/gps/position 0. 0. -81.2042 m
/run/beamOn 1
/gps/particle electron
/gps/number 1
/gps/direction 0 0 0.223798
/gps/ene/mono 0.107802 MeV
/gps/position 0. 0. -72.529 m
/run/beamOn 1
/gps/particle electron
/gps/number 1
/gps/direction 0 0 0.451552
/gps/ene/mono 0.138206 MeV
/gps/position 0. 0. -68.6348 m
/run/beamOn 1
/gps/particle electron
/gps/number 1
/gps/direction 0 0 0.525018
/gps/ene/mono 0.250452 MeV
/gps/position 0. 0. -16.0411 m
/run/beamOn 1
/gps/particle electron
/gps/number 1
/gps/direction 0 0 0.397341
/gps/ene/mono 0.266987 MeV
/gps/position 0. 0. 65.6048 m
/run/beamOn 1
/gps/particle electron
/gps/number 1
/gps/direction 0 0 0.594829
/gps/ene/mono 0.432807 MeV
/gps/position 0. 0. 94.248 m
/run/beamOn 1
/gps/particle electron
/gps/number 1
/gps/direction 0 0 0.377847
/gps/ene/mono 0.131501 MeV
/gps/position 0. 0. 192.796 m
/run/beamOn 1
/gps/particle electron
/gps/number 1
/gps/direction 0 0 0.335411
/gps/ene/mono 0.166929 MeV
/gps/position 0. 0. 198.469 m
/run/beamOn 1
/gps/particle electron
/gps/number 1
/gps/direction 0 0 0.458805
/gps/ene/mono 0.218075 MeV
/gps/position 0. 0. 199.175 m
/run/beamOn 1
/gps/particle electron
/gps/number 1
/gps/direction 0 0 0.357419
/gps/ene/mono 0.153558 MeV
/gps/position 0. 0. 301.787 m
/run/beamOn 1
/gps/particle electron
/gps/number 1
/gps/direction 0 0 0.563103
/gps/ene/mono 0.31645 MeV
/gps/position 0. 0. 320.577 m
/run/beamOn 1
/gps/particle electron
/gps/number 1
/gps/direction 0 0 0.362889
/gps/ene/mono 0.166426 MeV
/gps/position 0. 0. 332.685 m
/run/beamOn 1
/gps/particle electron
/gps/number 1
/gps/direction 0 0 0.957211
/gps/ene/mono 1.38355 MeV
/gps/position 0. 0. 291.103 m
/run/beamOn 1
/gps/particle electron
/gps/number 1
/gps/direction 0 0 0.0432254
/gps/ene/mono 0.168595 MeV
/gps/position 0. 0. -267.131 m
/run/beamOn 1
/gps/particle electron
/gps/number 1
/gps/direction 0 0 0.411585
/gps/ene/mono 0.249405 MeV
/gps/position 0. 0. -115.049 m
/run/beamOn 1
/gps/particle electron
/gps/number 1
/gps/direction 0 0 0.410331
/gps/ene/mono 0.323955 MeV
/gps/position 0. 0. -75.4066 m
/run/beamOn 1
/gps/particle electron
/gps/number 1
/gps/direction 0 0 0.340187
/gps/ene/mono 0.153938 MeV
/gps/position 0. 0. -49.3015 m
/run/beamOn 1
/gps/particle electron
/gps/number 1
/gps/direction 0 0 0.246855
/gps/ene/mono 0.115016 MeV
/gps/position 0. 0. -44.8568 m
/run/beamOn 1
/gps/particle electron
/gps/number 1
/gps/direction 0 0 0.401025
/gps/ene/mono 0.155385 MeV
/gps/position 0. 0. -43.0559 m
/run/beamOn 1
/gps/particle electron
/gps/number 1
/gps/direction 0 0 0.297092
/gps/ene/mono 0.111272 MeV
/gps/position 0. 0. -22.0122 m
/run/beamOn 1
/gps/particle electron
/gps/number 1
/gps/direction 0 0 0.345266
/gps/ene/mono 0.103143 MeV
/gps/position 0. 0. 27.4854 m
/run/beamOn 1
/gps/particle electron
/gps/number 1
/gps/direction 0 0 0.402964
/gps/ene/mono 0.232624 MeV
/gps/position 0. 0. 54.0456 m
/run/beamOn 1
/gps/particle electron
/gps/number 1
/gps/direction 0 0 0.502631
/gps/ene/mono 0.322647 MeV
/gps/position 0. 0. 101.402 m
/run/beamOn 1
/gps/particle electron
/gps/number 1
/gps/direction 0 0 0.438675
/gps/ene/mono 0.154146 MeV
/gps/position 0. 0. 113.755 m
/run/beamOn 1
/gps/particle electron
/gps/number 1
/gps/direction 0 0 0.554657
/gps/ene/mono 0.678319 MeV
/gps/position 0. 0. 127.738 m
/run/beamOn 1
/gps/particle electron
/gps/number 1
/gps/direction 0 0 0.507221
/gps/ene/mono 0.351334 MeV
/gps/position 0. 0. 133.546 m
/run/beamOn 1
/gps/particle electron
/gps/number 1
/gps/direction 0 0 0.431049
/gps/ene/mono 0.142141 MeV
/gps/position 0. 0. 137.598 m
/run/beamOn 1
/gps/particle electron
/gps/number 1
/gps/direction 0 0 0.510101
/gps/ene/mono 0.420409 MeV
/gps/position 0. 0. 151.481 m
/run/beamOn 1
/gps/particle electron
/gps/number 1
/gps/direction 0 0 0.360454
/gps/ene/mono 0.157342 MeV
/gps/position 0. 0. 181.153 m
/run/beamOn 1
/gps/particle electron
/gps/number 1
/gps/direction 0 0 0.458343
/gps/ene/mono 0.223179 MeV
/gps/position 0. 0. 234.322 m
/run/beamOn 1
/gps/particle electron
/gps/number 1
/gps/direction 0 0 0.357322
/gps/ene/mono 0.196248 MeV
/gps/position 0. 0. 296.886 m
/run/beamOn 1
/gps/particle electron
/gps/number 1
/gps/direction 0 0 0.441793
/gps/ene/mono 0.256554 MeV
/gps/position 0. 0. 298.365 m
/run/beamOn 1
/gps/particle electron
/gps/number 1
/gps/direction 0 0 0.345017
/gps/ene/mono 0.111345 MeV
/gps/position 0. 0. 334.809 m
/run/beamOn 1
/gps/particle electron
/gps/number 1
/gps/direction 0 0 0.553734
/gps/ene/mono 0.142625 MeV
/gps/position 0. 0. -98.9916 m
/run/beamOn 1
/gps/particle electron
/gps/number 1
/gps/direction 0 0 0.65377
/gps/ene/mono 0.446461 MeV
/gps/position 0. 0. -29.6339 m
/run/beamOn 1
/gps/particle electron
/gps/number 1
/gps/direction 0 0 0.752529
/gps/ene/mono 0.131295 MeV
/gps/position 0. 0. -265.522 m
/run/beamOn 1
/gps/particle electron
/gps/number 1
/gps/direction 0 0 0.882664
/gps/ene/mono 0.282048 MeV
/gps/position 0. 0. -256.941 m
/run/beamOn 1
/gps/particle electron
/gps/number 1
/gps/direction 0 0 0.387699
/gps/ene/mono 0.102265 MeV
/gps/position 0. 0. -249.863 m
/run/beamOn 1
/gps/particle electron
/gps/number 1
/gps/direction 0 0 0.85064
/gps/ene/mono 0.494953 MeV
/gps/position 0. 0. -247.105 m
/run/beamOn 1
/gps/particle electron
/gps/number 1
/gps/direction 0 0 0.696069
/gps/ene/mono 0.389716 MeV
/gps/position 0. 0. -211.612 m
/run/beamOn 1
/gps/particle electron
/gps/number 1
/gps/direction 0 0 0.259744
/gps/ene/mono 0.320335 MeV
/gps/position 0. 0. -196.396 m
/run/beamOn 1
/gps/particle electron
/gps/number 1
/gps/direction 0 0 0.383787
/gps/ene/mono 0.121829 MeV
/gps/position 0. 0. -141.611 m
/run/beamOn 1
/gps/particle electron
/gps/number 1
/gps/direction 0 0 0.304993
/gps/ene/mono 0.108221 MeV
/gps/position 0. 0. -129.193 m
/run/beamOn 1
/gps/particle electron
/gps/number 1
/gps/direction 0 0 0.328402
/gps/ene/mono 0.125469 MeV
/gps/position 0. 0. -111.678 m
/run/beamOn 1
/gps/particle electron
/gps/number 1
/gps/direction 0 0 0.244312
/gps/ene/mono 0.112224 MeV
/gps/position 0. 0. -108.59 m
/run/beamOn 1
/gps/particle electron
/gps/number 1
/gps/direction 0 0 0.470896
/gps/ene/mono 0.437714 MeV
/gps/position 0. 0. -98.2314 m
/run/beamOn 1
/gps/particle electron
/gps/number 1
/gps/direction 0 0 0.345467
/gps/ene/mono 0.131434 MeV
/gps/position 0. 0. -57.9268 m
/run/beamOn 1
/gps/particle electron
/gps/number 1
/gps/direction 0 0 0.666675
/gps/ene/mono 0.558774 MeV
/gps/position 0. 0. -37.4321 m
/run/beamOn 1
/gps/particle electron
/gps/number 1
/gps/direction 0 0 0.403144
/gps/ene/mono 0.144131 MeV
/gps/position 0. 0. -34.9983 m
/run/beamOn 1
/gps/particle electron
/gps/number 1
/gps/direction 0 0 0.48243
/gps/ene/mono 0.280279 MeV
/gps/position 0. 0. -22.6665 m
/run/beamOn 1
/gps/particle electron
/gps/number 1
/gps/direction 0 0 0.476174
/gps/ene/mono 0.223296 MeV
/gps/position 0. 0. 2.72283 m
/run/beamOn 1
/gps/particle electron
/gps/number 1
/gps/direction 0 0 0.529032
/gps/ene/mono 0.315831 MeV
/gps/position 0. 0. 12.9814 m
/run/beamOn 1
/gps/particle electron
/gps/number 1
/gps/direction 0 0 0.323252
/gps/ene/mono 0.120022 MeV
/gps/position 0. 0. 74.7157 m
/run/beamOn 1
/gps/particle electron
/gps/number 1
/gps/direction 0 0 0.860069
/gps/ene/mono 3.1871 MeV
/gps/position 0. 0. 84.9594 m
/run/beamOn 1
/gps/particle electron
/gps/number 1
/gps/direction 0 0 0.359581
/gps/ene/mono 0.161929 MeV
/gps/position 0. 0. 89.0723 m
/run/beamOn 1
/gps/particle electron
/gps/number 1
/gps/direction 0 0 0.36507
/gps/ene/mono 0.127992 MeV
/gps/position 0. 0. 99.2532 m
/run/beamOn 1
/gps/particle electron
/gps/number 1
/gps/direction 0 0 0.46305
/gps/ene/mono 0.183059 MeV
/gps/position 0. 0. 101.447 m
/run/beamOn 1
/gps/particle electron
/gps/number 1
/gps/direction 0 0 0.477892
/gps/ene/mono 0.22441 MeV
/gps/position 0. 0. 135.146 m
/run/beamOn 1
/gps/particle electron
/gps/number 1
/gps/direction 0 0 0.308333
/gps/ene/mono 0.177406 MeV
/gps/position 0. 0. 234.904 m
/run/beamOn 1
/gps/particle electron
/gps/number 1
/gps/direction 0 0 0.496399
/gps/ene/mono 0.447388 MeV
/gps/position 0. 0. 288.299 m
/run/beamOn 1
/gps/particle electron
/gps/number 1
/gps/direction 0 0 0.573242
/gps/ene/mono 0.269907 MeV
/gps/position 0. 0. 306.208 m
/run/beamOn 1
/gps/particle electron
/gps/number 1
/gps/direction 0 0 0.368198
/gps/ene/mono 0.137611 MeV
/gps/position 0. 0. 310.63 m
/run/beamOn 1
/gps/particle electron
/gps/number 1
/gps/direction 0 0 0.920072
/gps/ene/mono 0.550373 MeV
/gps/position 0. 0. 181.111 m
/run/beamOn 1
/gps/particle electron
/gps/number 1
/gps/direction 0 0 0.874717
/gps/ene/mono 0.731663 MeV
/gps/position 0. 0. 73.9624 m
/run/beamOn 1
/gps/particle electron
/gps/number 1
/gps/direction 0 0 0.838587
/gps/ene/mono 1.12405 MeV
/gps/position 0. 0. 301.133 m
/run/beamOn 1
/gps/particle electron
/gps/number 1
/gps/direction 0 0 0.443685
/gps/ene/mono 0.135567 MeV
/gps/position 0. 0. -206.417 m
/run/beamOn 1
/gps/particle electron
/gps/number 1
/gps/direction 0 0 0.790125
/gps/ene/mono 0.75246 MeV
/gps/position 0. 0. -116.474 m
/run/beamOn 1
/gps/particle electron
/gps/number 1
/gps/direction 0 0 0.681359
/gps/ene/mono 0.438698 MeV
/gps/position 0. 0. -43.2429 m
/run/beamOn 1
/gps/particle electron
/gps/number 1
/gps/direction 0 0 0.709247
/gps/ene/mono 1.0316 MeV
/gps/position 0. 0. 8.32302 m
/run/beamOn 1
/gps/particle electron
/gps/number 1
/gps/direction 0 0 0.457802
/gps/ene/mono 0.189017 MeV
/gps/position 0. 0. 36.1982 m
/run/beamOn 1
/gps/particle electron
/gps/number 1
/gps/direction 0 0 0.272596
/gps/ene/mono 0.107691 MeV
/gps/position 0. 0. 77.2533 m
/run/beamOn 1
/gps/particle electron
/gps/number 1
/gps/direction 0 0 0.22092
/gps/ene/mono 0.100131 MeV
/gps/position 0. 0. 91.0176 m
/run/beamOn 1
/gps/particle electron
/gps/number 1
/gps/direction 0 0 0.105386
/gps/ene/mono 0.100826 MeV
/gps/position 0. 0. 104.758 m
/run/beamOn 1
/gps/particle electron
/gps/number 1
/gps/direction 0 0 0.742583
/gps/ene/mono 0.764573 MeV
/gps/position 0. 0. 108.792 m
/run/beamOn 1
/gps/particle electron
/gps/number 1
/gps/direction 0 0 0.682487
/gps/ene/mono 0.360659 MeV
/gps/position 0. 0. 116.131 m
/run/beamOn 1
/gps/particle electron
/gps/number 1
/gps/direction 0 0 0.518941
/gps/ene/mono 0.110812 MeV
/gps/position 0. 0. 122.429 m
/run/beamOn 1
/gps/particle electron
/gps/number 1
/gps/direction 0 0 0.544965
/gps/ene/mono 0.159174 MeV
/gps/position 0. 0. 135.436 m
/run/beamOn 1
/gps/particle electron
/gps/number 1
/gps/direction 0 0 0.6062
/gps/ene/mono 0.373769 MeV
/gps/position 0. 0. 145.096 m
/run/beamOn 1
/gps/particle electron
/gps/number 1
/gps/direction 0 0 0.212624
/gps/ene/mono 0.111242 MeV
/gps/position 0. 0. 181.156 m
/run/beamOn 1
/gps/particle electron
/gps/number 1
/gps/direction 0 0 0.522413
/gps/ene/mono 0.402322 MeV
/gps/position 0. 0. 219.526 m
/run/beamOn 1
/gps/particle electron
/gps/number 1
/gps/direction 0 0 0.73974
/gps/ene/mono 0.851948 MeV
/gps/position 0. 0. 251.104 m
/run/beamOn 1
/gps/particle electron
/gps/number 1
/gps/direction 0 0 0.321346
/gps/ene/mono 0.138964 MeV
/gps/position 0. 0. 254.599 m
/run/beamOn 1
/gps/particle electron
/gps/number 1
/gps/direction 0 0 0.214622
/gps/ene/mono 0.126487 MeV
/gps/position 0. 0. 254.805 m
/run/beamOn 1
/gps/particle electron
/gps/number 1
/gps/direction 0 0 0.325329
/gps/ene/mono 0.242842 MeV
/gps/position 0. 0. 260.197 m
/run/beamOn 1
/gps/particle electron
/gps/number 1
/gps/direction 0 0 0.405755
/gps/ene/mono 0.157864 MeV
/gps/position 0. 0. 346.384 m
/run/beamOn 1
/gps/particle electron
/gps/number 1
/gps/direction 0 0 0.840967
/gps/ene/mono 0.470468 MeV
/gps/position 0. 0. 268.89 m
/run/beamOn 1
/gps/particle electron
/gps/number 1
/gps/direction 0 0 0.293641
/gps/ene/mono 0.160648 MeV
/gps/position 0. 0. -319.322 m
/run/beamOn 1
/gps/particle electron
/gps/number 1
/gps/direction 0 0 0.224975
/gps/ene/mono 0.108781 MeV
/gps/position 0. 0. -249.898 m
/run/beamOn 1
/gps/particle electron
/gps/number 1
/gps/direction 0 0 0.512496
/gps/ene/mono 0.406415 MeV
/gps/position 0. 0. -179.031 m
/run/beamOn 1
/gps/particle electron
/gps/number 1
/gps/direction 0 0 0.243489
/gps/ene/mono 0.113659 MeV
/gps/position 0. 0. -136.582 m
/run/beamOn 1
/gps/particle electron
/gps/number 1
/gps/direction 0 0 0.315496
/gps/ene/mono 0.18474 MeV
/gps/position 0. 0. -122.202 m
/run/beamOn 1
/gps/particle electron
/gps/number 1
/gps/direction 0 0 0.492698
/gps/ene/mono 0.129152 MeV
/gps/position 0. 0. -91.1013 m
/run/beamOn 1
/gps/particle electron
/gps/number 1
/gps/direction 0 0 0.293496
/gps/ene/mono 0.250873 MeV
/gps/position 0. 0. -88.0504 m
/run/beamOn 1
/gps/particle electron
/gps/number 1
/gps/direction 0 0 0.516498
/gps/ene/mono 0.17804 MeV
/gps/position 0. 0. -57.0315 m
/run/beamOn 1
/gps/particle electron
/gps/number 1
/gps/direction 0 0 0.41343
/gps/ene/mono 0.102079 MeV
/gps/position 0. 0. -51.7951 m
/run/beamOn 1
/gps/particle electron
/gps/number 1
/gps/direction 0 0 0.901856
/gps/ene/mono 2.48848 MeV
/gps/position 0. 0. -42.3772 m
/run/beamOn 1
/gps/particle electron
/gps/number 1
/gps/direction 0 0 0.565067
/gps/ene/mono 0.454596 MeV
/gps/position 0. 0. -11.1604 m
/run/beamOn 1
/gps/particle electron
/gps/number 1
/gps/direction 0 0 0.923313
/gps/ene/mono 2.94169 MeV
/gps/position 0. 0. -3.19235 m
/run/beamOn 1
/gps/particle electron
/gps/number 1
/gps/direction 0 0 0.217191
/gps/ene/mono 0.134082 MeV
/gps/position 0. 0. 39.1498 m
/run/beamOn 1
/gps/particle electron
/gps/number 1
/gps/direction 0 0 0.446973
/gps/ene/mono 0.140903 MeV
/gps/position 0. 0. 40.3445 m
/run/beamOn 1
/gps/particle electron
/gps/number 1
/gps/direction 0 0 0.352341
/gps/ene/mono 0.260226 MeV
/gps/position 0. 0. 57.5714 m
/run/beamOn 1
/gps/particle electron
/gps/number 1
/gps/direction 0 0 0.433236
/gps/ene/mono 0.256179 MeV
/gps/position 0. 0. 59.9932 m
/run/beamOn 1
/gps/particle electron
/gps/number 1
/gps/direction 0 0 0.721332
/gps/ene/mono 0.757144 MeV
/gps/position 0. 0. 61.1777 m
/run/beamOn 1
/gps/particle electron
/gps/number 1
/gps/direction 0 0 0.420209
/gps/ene/mono 0.128302 MeV
/gps/position 0. 0. 82.9698 m
/run/beamOn 1
/gps/particle electron
/gps/number 1
/gps/direction 0 0 0.602604
/gps/ene/mono 0.550661 MeV
/gps/position 0. 0. 96.4303 m
/run/beamOn 1
/gps/particle electron
/gps/number 1
/gps/direction 0 0 0.650691
/gps/ene/mono 1.43241 MeV
/gps/position 0. 0. 105.162 m
/run/beamOn 1
/gps/particle electron
/gps/number 1
/gps/direction 0 0 0.264057
/gps/ene/mono 0.108978 MeV
/gps/position 0. 0. 122.043 m
/run/beamOn 1
/gps/particle electron
/gps/number 1
/gps/direction 0 0 0.443787
/gps/ene/mono 0.183453 MeV
/gps/position 0. 0. 134.423 m
/run/beamOn 1
/gps/particle electron
/gps/number 1
/gps/direction 0 0 0.543205
/gps/ene/mono 0.620389 MeV
/gps/position 0. 0. 197.902 m
/run/beamOn 1
/gps/particle electron
/gps/number 1
/gps/direction 0 0 0.312604
/gps/ene/mono 0.108269 MeV
/gps/position 0. 0. 232.358 m
/run/beamOn 1
/gps/particle electron
/gps/number 1
/gps/direction 0 0 0.429546
/gps/ene/mono 0.174944 MeV
/gps/position 0. 0. 305.942 m
/run/beamOn 1
/gps/particle electron
/gps/number 1
/gps/direction 0 0 -0.493021
/gps/ene/mono 0.303734 MeV
/gps/position 0. 0. -276.59 m
/run/beamOn 1
/gps/particle electron
/gps/number 1
/gps/direction 0 0 0.914672
/gps/ene/mono 0.118225 MeV
/gps/position 0. 0. -270.573 m
/run/beamOn 1
/gps/particle electron
/gps/number 1
/gps/direction 0 0 0.609396
/gps/ene/mono 0.226447 MeV
/gps/position 0. 0. -257.71 m
/run/beamOn 1
/gps/particle electron
/gps/number 1
/gps/direction 0 0 0.488846
/gps/ene/mono 0.115793 MeV
/gps/position 0. 0. -220.802 m
/run/beamOn 1
/gps/particle electron
/gps/number 1
/gps/direction 0 0 0.419441
/gps/ene/mono 0.152822 MeV
/gps/position 0. 0. -157.408 m
/run/beamOn 1
/gps/particle electron
/gps/number 1
/gps/direction 0 0 0.638428
/gps/ene/mono 0.386214 MeV
/gps/position 0. 0. -156.197 m
/run/beamOn 1
/gps/particle electron
/gps/number 1
/gps/direction 0 0 0.42721
/gps/ene/mono 0.214083 MeV
/gps/position 0. 0. -109.818 m
/run/beamOn 1
/gps/particle electron
/gps/number 1
/gps/direction 0 0 0.727935
/gps/ene/mono 0.155366 MeV
/gps/position 0. 0. -72.9407 m
/run/beamOn 1
/gps/particle electron
/gps/number 1
/gps/direction 0 0 0.348742
/gps/ene/mono 0.478176 MeV
/gps/position 0. 0. -67.9336 m
/run/beamOn 1
/gps/particle electron
/gps/number 1
/gps/direction 0 0 0.107342
/gps/ene/mono 0.254469 MeV
/gps/position 0. 0. -56.8873 m
/run/beamOn 1
/gps/particle electron
/gps/number 1
/gps/direction 0 0 0.448871
/gps/ene/mono 0.582842 MeV
/gps/position 0. 0. -48.7116 m
/run/beamOn 1
/gps/particle electron
/gps/number 1
/gps/direction 0 0 0.442526
/gps/ene/mono 0.88533 MeV
/gps/position 0. 0. -40.2412 m
/run/beamOn 1
/gps/particle electron
/gps/number 1
/gps/direction 0 0 0.0606885
/gps/ene/mono 0.103408 MeV
/gps/position 0. 0. -33.5925 m
/run/beamOn 1
/gps/particle electron
/gps/number 1
/gps/direction 0 0 0.142469
/gps/ene/mono 0.180394 MeV
/gps/position 0. 0. 34.6157 m
/run/beamOn 1
/gps/particle electron
/gps/number 1
/gps/direction 0 0 0.641493
/gps/ene/mono 0.14366 MeV
/gps/position 0. 0. 105.827 m
/run/beamOn 1
/gps/particle electron
/gps/number 1
/gps/direction 0 0 0.67284
/gps/ene/mono 0.178066 MeV
/gps/position 0. 0. 107.907 m
/run/beamOn 1
/gps/particle electron
/gps/number 1
/gps/direction 0 0 0.275792
/gps/ene/mono 0.428549 MeV
/gps/position 0. 0. 111.249 m
/run/beamOn 1
/gps/particle electron
/gps/number 1
/gps/direction 0 0 0.392378
/gps/ene/mono 0.195752 MeV
/gps/position 0. 0. 119.661 m
/run/beamOn 1
/gps/particle electron
/gps/number 1
/gps/direction 0 0 0.272699
/gps/ene/mono 0.317319 MeV
/gps/position 0. 0. 155.878 m
/run/beamOn 1
/gps/particle electron
/gps/number 1
/gps/direction 0 0 0.620997
/gps/ene/mono 0.106935 MeV
/gps/position 0. 0. 205.767 m
/run/beamOn 1
/gps/particle electron
/gps/number 1
/gps/direction 0 0 0.155743
/gps/ene/mono 0.199097 MeV
/gps/position 0. 0. 257.994 m
/run/beamOn 1
/gps/particle electron
/gps/number 1
/gps/direction 0 0 0.560374
/gps/ene/mono 0.117223 MeV
/gps/position 0. 0. 259.189 m
/run/beamOn 1
/gps/particle electron
/gps/number 1
/gps/direction 0 0 0.455286
/gps/ene/mono 0.186717 MeV
/gps/position 0. 0. 263.066 m
/run/beamOn 1
/gps/particle electron
/gps/number 1
/gps/direction 0 0 0.987486
/gps/ene/mono 0.303281 MeV
/gps/position 0. 0. 296.879 m
/run/beamOn 1
/gps/particle electron
/gps/number 1
/gps/direction 0 0 0.494225
/gps/ene/mono 0.209841 MeV
/gps/position 0. 0. -255.357 m
/run/beamOn 1
/gps/particle electron
/gps/number 1
/gps/direction 0 0 0.0752782
/gps/ene/mono 0.412219 MeV
/gps/position 0. 0. -238.335 m
/run/beamOn 1
/gps/particle electron
/gps/number 1
/gps/direction 0 0 0.497596
/gps/ene/mono 0.111021 MeV
/gps/position 0. 0. -232.963 m
/run/beamOn 1
/gps/particle electron
/gps/number 1
/gps/direction 0 0 0.694551
/gps/ene/mono 0.606513 MeV
/gps/position 0. 0. -213.865 m
/run/beamOn 1
/gps/particle electron
/gps/number 1
/gps/direction 0 0 0.943366
/gps/ene/mono 4.29451 MeV
/gps/position 0. 0. -194.177 m
/run/beamOn 1
/gps/particle electron
/gps/number 1
/gps/direction 0 0 0.585785
/gps/ene/mono 0.181861 MeV
/gps/position 0. 0. -72.2992 m
/run/beamOn 1
/gps/particle electron
/gps/number 1
/gps/direction 0 0 0.382414
/gps/ene/mono 0.138301 MeV
/gps/position 0. 0. -10.5138 m
/run/beamOn 1
/gps/particle electron
/gps/number 1
/gps/direction 0 0 0.0519206
/gps/ene/mono 0.107795 MeV
/gps/position 0. 0. -9.5513 m
/run/beamOn 1
/gps/particle electron
/gps/number 1
/gps/direction 0 0 0.285358
/gps/ene/mono 0.102345 MeV
/gps/position 0. 0. -2.54863 m
/run/beamOn 1
/gps/particle electron
/gps/number 1
/gps/direction 0 0 0.327418
/gps/ene/mono 0.293331 MeV
/gps/position 0. 0. 27.2752 m
/run/beamOn 1
/gps/particle electron
/gps/number 1
/gps/direction 0 0 0.448985
/gps/ene/mono 0.161213 MeV
/gps/position 0. 0. 65.2055 m
/run/beamOn 1
/gps/particle electron
/gps/number 1
/gps/direction 0 0 0.393816
/gps/ene/mono 0.313422 MeV
/gps/position 0. 0. 69.905 m
/run/beamOn 1
/gps/particle electron
/gps/number 1
/gps/direction 0 0 0.787322
/gps/ene/mono 0.916252 MeV
/gps/position 0. 0. 155.324 m
/run/beamOn 1
/gps/particle electron
/gps/number 1
/gps/direction 0 0 0.254245
/gps/ene/mono 0.123812 MeV
/gps/position 0. 0. 168.857 m
/run/beamOn 1
/gps/particle electron
/gps/number 1
/gps/direction 0 0 0.652898
/gps/ene/mono 1.03765 MeV
/gps/position 0. 0. 242.685 m
/run/beamOn 1
/gps/particle electron
/gps/number 1
/gps/direction 0 0 0.331454
/gps/ene/mono 0.102384 MeV
/gps/position 0. 0. 269.815 m
/run/beamOn 1
/gps/particle electron
/gps/number 1
/gps/direction 0 0 0.279703
/gps/ene/mono 0.114118 MeV
/gps/position 0. 0. 271.515 m
/run/beamOn 1
/gps/particle electron
/gps/number 1
/gps/direction 0 0 0.511635
/gps/ene/mono 0.362739 MeV
/gps/position 0. 0. 297.579 m
/run/beamOn 1
/gps/particle electron
/gps/number 1
/gps/direction 0 0 0.388884
/gps/ene/mono 0.232267 MeV
/gps/position 0. 0. 303.219 m
/run/beamOn 1
/gps/particle electron
/gps/number 1
/gps/direction 0 0 0.975075
/gps/ene/mono 0.668411 MeV
/gps/position 0. 0. 274.094 m
/run/beamOn 1
/gps/particle electron
/gps/number 1
/gps/direction 0 0 0.872734
/gps/ene/mono 0.37459 MeV
/gps/position 0. 0. -14.8554 m
/run/beamOn 1
/gps/particle electron
/gps/number 1
/gps/direction 0 0 0.994242
/gps/ene/mono 0.156421 MeV
/gps/position 0. 0. -136.293 m
/run/beamOn 1
/gps/particle electron
/gps/number 1
/gps/direction 0 0 0.836154
/gps/ene/mono 0.161917 MeV
/gps/position 0. 0. -125.592 m
/run/beamOn 1
/gps/particle electron
/gps/number 1
/gps/direction 0 0 0.0437815
/gps/ene/mono 0.108351 MeV
/gps/position 0. 0. -123.591 m
/run/beamOn 1
/gps/particle electron
/gps/number 1
/gps/direction 0 0 0.682482
/gps/ene/mono 0.514993 MeV
/gps/position 0. 0. -105.55 m
/run/beamOn 1
/gps/particle electron
/gps/number 1
/gps/direction 0 0 0.0525209
/gps/ene/mono 0.117024 MeV
/gps/position 0. 0. -102.602 m
/run/beamOn 1
/gps/particle electron
/gps/number 1
/gps/direction 0 0 0.404941
/gps/ene/mono 0.161896 MeV
/gps/position 0. 0. -67.7891 m
/run/beamOn 1
/gps/particle electron
/gps/number 1
/gps/direction 0 0 0.308358
/gps/ene/mono 0.109587 MeV
/gps/position 0. 0. -63.8576 m
/run/beamOn 1
/gps/particle electron
/gps/number 1
/gps/direction 0 0 0.348101
/gps/ene/mono 0.104663 MeV
/gps/position 0. 0. -54.2581 m
/run/beamOn 1
/gps/particle electron
/gps/number 1
/gps/direction 0 0 0.467727
/gps/ene/mono 0.166508 MeV
/gps/position 0. 0. -37.309 m
/run/beamOn 1
/gps/particle electron
/gps/number 1
/gps/direction 0 0 0.657349
/gps/ene/mono 0.740851 MeV
/gps/position 0. 0. -9.54944 m
/run/beamOn 1
/gps/particle electron
/gps/number 1
/gps/direction 0 0 0.551942
/gps/ene/mono 0.689309 MeV
/gps/position 0. 0. 20.4433 m
/run/beamOn 1
/gps/particle electron
/gps/number 1
/gps/direction 0 0 0.0179087
/gps/ene/mono 0.106806 MeV
/gps/position 0. 0. 36.2219 m
/run/beamOn 1
/gps/particle electron
/gps/number 1
/gps/direction 0 0 0.0555071
/gps/ene/mono 0.111006 MeV
/gps/position 0. 0. 42.3859 m
/run/beamOn 1
/gps/particle electron
/gps/number 1
/gps/direction 0 0 0.460864
/gps/ene/mono 1.1706 MeV
/gps/position 0. 0. 137.426 m
/run/beamOn 1
/gps/particle electron
/gps/number 1
/gps/direction 0 0 0.501544
/gps/ene/mono 0.169008 MeV
/gps/position 0. 0. 145.877 m
/run/beamOn 1
/gps/particle electron
/gps/number 1
/gps/direction 0 0 0.101353
/gps/ene/mono 0.157821 MeV
/gps/position 0. 0. 186.929 m
/run/beamOn 1
/gps/particle electron
/gps/number 1
/gps/direction 0 0 0.00328725
/gps/ene/mono 0.149997 MeV
/gps/position 0. 0. 260.083 m
/run/beamOn 1
/gps/particle electron
/gps/number 1
/gps/direction 0 0 0.6039
/gps/ene/mono 0.133479 MeV
/gps/position 0. 0. 280.317 m
/run/beamOn 1
/gps/particle electron
/gps/number 1
/gps/direction 0 0 0.588185
/gps/ene/mono 0.551241 MeV
/gps/position 0. 0. 293.553 m
/run/beamOn 1
/gps/particle electron
/gps/number 1
/gps/direction 0 0 0.45664
/gps/ene/mono 0.108987 MeV
/gps/position 0. 0. 347.001 m
/run/beamOn 1
/gps/particle electron
/gps/number 1
/gps/direction 0 0 0.954082
/gps/ene/mono 0.387394 MeV
/gps/position 0. 0. 221.074 m
/run/beamOn 1
/gps/particle electron
/gps/number 1
/gps/direction 0 0 -0.0651942
/gps/ene/mono 0.111671 MeV
/gps/position 0. 0. -197.874 m
/run/beamOn 1
/gps/particle electron
/gps/number 1
/gps/direction 0 0 0.941665
/gps/ene/mono 0.287687 MeV
/gps/position 0. 0. -260.683 m
/run/beamOn 1
/gps/particle electron
/gps/number 1
/gps/direction 0 0 -0.477443
/gps/ene/mono 0.257579 MeV
/gps/position 0. 0. -341.755 m
/run/beamOn 1
/gps/particle electron
/gps/number 1
/gps/direction 0 0 0.843041
/gps/ene/mono 0.250528 MeV
/gps/position 0. 0. -265.197 m
/run/beamOn 1
/gps/particle electron
/gps/number 1
/gps/direction 0 0 -0.0473404
/gps/ene/mono 0.128267 MeV
/gps/position 0. 0. -260.248 m
/run/beamOn 1
/gps/particle electron
/gps/number 1
/gps/direction 0 0 0.498439
/gps/ene/mono 0.142699 MeV
/gps/position 0. 0. -173.225 m
/run/beamOn 1
/gps/particle electron
/gps/number 1
/gps/direction 0 0 0.846635
/gps/ene/mono 0.215755 MeV
/gps/position 0. 0. -84.4444 m
/run/beamOn 1
/gps/particle electron
/gps/number 1
/gps/direction 0 0 -0.591871
/gps/ene/mono 0.126228 MeV
/gps/position 0. 0. -160.817 m
/run/beamOn 1
/gps/particle electron
/gps/number 1
/gps/direction 0 0 -0.650299
/gps/ene/mono 0.533396 MeV
/gps/position 0. 0. -332.134 m
/run/beamOn 1
/gps/particle electron
/gps/number 1
/gps/direction 0 0 0.32654
/gps/ene/mono 0.109332 MeV
/gps/position 0. 0. -336.872 m
/run/beamOn 1
/gps/particle electron
/gps/number 1
/gps/direction 0 0 0.736768
/gps/ene/mono 0.379709 MeV
/gps/position 0. 0. -331.313 m
/run/beamOn 1
/gps/particle electron
/gps/number 1
/gps/direction 0 0 -0.432548
/gps/ene/mono 0.148584 MeV
/gps/position 0. 0. -319.981 m
/run/beamOn 1
/gps/particle electron
/gps/number 1
/gps/direction 0 0 0.28306
/gps/ene/mono 0.356412 MeV
/gps/position 0. 0. -301.116 m
/run/beamOn 1
/gps/particle electron
/gps/number 1
/gps/direction 0 0 0.281248
/gps/ene/mono 0.150416 MeV
/gps/position 0. 0. -286.972 m
/run/beamOn 1
/gps/particle electron
/gps/number 1
/gps/direction 0 0 0.161926
/gps/ene/mono 0.121558 MeV
/gps/position 0. 0. -270.755 m
/run/beamOn 1
/gps/particle electron
/gps/number 1
/gps/direction 0 0 0.421697
/gps/ene/mono 0.205387 MeV
/gps/position 0. 0. -210.949 m
/run/beamOn 1
/gps/particle electron
/gps/number 1
/gps/direction 0 0 0.464915
/gps/ene/mono 0.286767 MeV
/gps/position 0. 0. -208.439 m
/run/beamOn 1
/gps/particle electron
/gps/number 1
/gps/direction 0 0 0.478669
/gps/ene/mono 0.144828 MeV
/gps/position 0. 0. -197.345 m
/run/beamOn 1
/gps/particle electron
/gps/number 1
/gps/direction 0 0 0.622037
/gps/ene/mono 0.293046 MeV
/gps/position 0. 0. -165.658 m
/run/beamOn 1
/gps/particle electron
/gps/number 1
/gps/direction 0 0 0.411148
/gps/ene/mono 0.219167 MeV
/gps/position 0. 0. -140.388 m
/run/beamOn 1
/gps/particle electron
/gps/number 1
/gps/direction 0 0 0.50467
/gps/ene/mono 0.233513 MeV
/gps/position 0. 0. -86.3157 m
/run/beamOn 1
/gps/particle electron
/gps/number 1
/gps/direction 0 0 0.377908
/gps/ene/mono 0.12154 MeV
/gps/position 0. 0. 15.6191 m
/run/beamOn 1
/gps/particle electron
/gps/number 1
/gps/direction 0 0 0.296128
/gps/ene/mono 0.174865 MeV
/gps/position 0. 0. 46.3448 m
/run/beamOn 1
/gps/particle electron
/gps/number 1
/gps/direction 0 0 0.290711
/gps/ene/mono 0.180434 MeV
/gps/position 0. 0. 54.8909 m
/run/beamOn 1
/gps/particle electron
/gps/number 1
/gps/direction 0 0 0.317457
/gps/ene/mono 0.115038 MeV
/gps/position 0. 0. 100.893 m
/run/beamOn 1
/gps/particle electron
/gps/number 1
/gps/direction 0 0 0.646848
/gps/ene/mono 1.26766 MeV
/gps/position 0. 0. 120.521 m
/run/beamOn 1
/gps/particle electron
/gps/number 1
/gps/direction 0 0 0.511091
/gps/ene/mono 0.707517 MeV
/gps/position 0. 0. 121.553 m
/run/beamOn 1
/gps/particle electron
/gps/number 1
/gps/direction 0 0 0.447415
/gps/ene/mono 0.155646 MeV
/gps/position 0. 0. 138.298 m
/run/beamOn 1
/gps/particle electron
/gps/number 1
/gps/direction 0 0 0.570846
/gps/ene/mono 0.186355 MeV
/gps/position 0. 0. 164.619 m
/run/beamOn 1
/gps/particle electron
/gps/number 1
/gps/direction 0 0 0.278165
/gps/ene/mono 0.253029 MeV
/gps/position 0. 0. 195.737 m
/run/beamOn 1
/gps/particle electron
/gps/number 1
/gps/direction 0 0 0.418977
/gps/ene/mono 0.187764 MeV
/gps/position 0. 0. 206.604 m
/run/beamOn 1
/gps/particle electron
/gps/number 1
/gps/direction 0 0 0.232684
/gps/ene/mono 0.105743 MeV
/gps/position 0. 0. 209.549 m
/run/beamOn 1
/gps/particle electron
/gps/number 1
/gps/direction 0 0 0.260105
/gps/ene/mono 0.10297 MeV
/gps/position 0. 0. 227.787 m
/run/beamOn 1
/gps/particle electron
/gps/number 1
/gps/direction 0 0 0.702649
/gps/ene/mono 0.995097 MeV
/gps/position 0. 0. 254.438 m
/run/beamOn 1
/gps/particle electron
/gps/number 1
/gps/direction 0 0 0.340968
/gps/ene/mono 0.109149 MeV
/gps/position 0. 0. 257.227 m
/run/beamOn 1
/gps/particle electron
/gps/number 1
/gps/direction 0 0 0.440315
/gps/ene/mono 0.204683 MeV
/gps/position 0. 0. 288.95 m
/run/beamOn 1
/gps/particle electron
/gps/number 1
/gps/direction 0 0 0.419551
/gps/ene/mono 0.166092 MeV
/gps/position 0. 0. 301.53 m
/run/beamOn 1
/gps/particle electron
/gps/number 1
/gps/direction 0 0 0.618839
/gps/ene/mono 0.292735 MeV
/gps/position 0. 0. 312.617 m
/run/beamOn 1
/gps/particle electron
/gps/number 1
/gps/direction 0 0 0.568388
/gps/ene/mono 0.170072 MeV
/gps/position 0. 0. 263.807 m
/run/beamOn 1
/gps/particle electron
/gps/number 1
/gps/direction 0 0 0.540046
/gps/ene/mono 0.340879 MeV
/gps/position 0. 0. 326.271 m
/run/beamOn 1
/gps/particle electron
/gps/number 1
/gps/direction 0 0 0.0440155
/gps/ene/mono 0.156707 MeV
/gps/position 0. 0. -85.9849 m
/run/beamOn 1
/gps/particle electron
/gps/number 1
/gps/direction 0 0 0.537888
/gps/ene/mono 0.100036 MeV
/gps/position 0. 0. 232.561 m
/run/beamOn 1
/gps/particle electron
/gps/number 1
/gps/direction 0 0 0.235888
/gps/ene/mono 0.181763 MeV
/gps/position 0. 0. -254.71 m
/run/beamOn 1
/gps/particle electron
/gps/number 1
/gps/direction 0 0 0.202237
/gps/ene/mono 0.101972 MeV
/gps/position 0. 0. -254.696 m
/run/beamOn 1
/gps/particle electron
/gps/number 1
/gps/direction 0 0 0.447133
/gps/ene/mono 0.183958 MeV
/gps/position 0. 0. -278.16 m
/run/beamOn 1
/gps/particle electron
/gps/number 1
/gps/direction 0 0 0.063356
/gps/ene/mono 0.101263 MeV
/gps/position 0. 0. -277.889 m
/run/beamOn 1
/gps/particle electron
/gps/number 1
/gps/direction 0 0 0.7605
/gps/ene/mono 0.156316 MeV
/gps/position 0. 0. -311.507 m
/run/beamOn 1
/gps/particle electron
/gps/number 1
/gps/direction 0 0 0.749354
/gps/ene/mono 0.169755 MeV
/gps/position 0. 0. -297.718 m
/run/beamOn 1
/gps/particle electron
/gps/number 1
/gps/direction 0 0 0.655186
/gps/ene/mono 0.276345 MeV
/gps/position 0. 0. -255.055 m
/run/beamOn 1
/gps/particle electron
/gps/number 1
/gps/direction 0 0 0.672771
/gps/ene/mono 0.119272 MeV
/gps/position 0. 0. -254.326 m
/run/beamOn 1
/gps/particle electron
/gps/number 1
/gps/direction 0 0 0.199515
/gps/ene/mono 0.115228 MeV
/gps/position 0. 0. -218.733 m
/run/beamOn 1
/gps/particle electron
/gps/number 1
/gps/direction 0 0 0.569673
/gps/ene/mono 0.154424 MeV
/gps/position 0. 0. -192.504 m
/run/beamOn 1
/gps/particle electron
/gps/number 1
/gps/direction 0 0 0.473071
/gps/ene/mono 0.129675 MeV
/gps/position 0. 0. -188.068 m
/run/beamOn 1
/gps/particle electron
/gps/number 1
/gps/direction 0 0 0.586311
/gps/ene/mono 0.448789 MeV
/gps/position 0. 0. -171.358 m
/run/beamOn 1
/gps/particle electron
/gps/number 1
/gps/direction 0 0 0.347863
/gps/ene/mono 0.110965 MeV
/gps/position 0. 0. -140.765 m
/run/beamOn 1
/gps/particle electron
/gps/number 1
/gps/direction 0 0 0.944501
/gps/ene/mono 5.04519 MeV
/gps/position 0. 0. -122.36 m
/run/beamOn 1
/gps/particle electron
/gps/number 1
/gps/direction 0 0 0.504347
/gps/ene/mono 0.279326 MeV
/gps/position 0. 0. -108.995 m
/run/beamOn 1
/gps/particle electron
/gps/number 1
/gps/direction 0 0 0.347488
/gps/ene/mono 0.117767 MeV
/gps/position 0. 0. -88.0125 m
/run/beamOn 1
/gps/particle electron
/gps/number 1
/gps/direction 0 0 0.423555
/gps/ene/mono 0.489604 MeV
/gps/position 0. 0. -47.2095 m
/run/beamOn 1
/gps/particle electron
/gps/number 1
/gps/direction 0 0 0.468552
/gps/ene/mono 0.144126 MeV
/gps/position 0. 0. -16.466 m
/run/beamOn 1
/gps/particle electron
/gps/number 1
/gps/direction 0 0 0.355108
/gps/ene/mono 0.145413 MeV
/gps/position 0. 0. 45.9217 m
/run/beamOn 1
/gps/particle electron
/gps/number 1
/gps/direction 0 0 0.569797
/gps/ene/mono 0.369876 MeV
/gps/position 0. 0. 54.2445 m
/run/beamOn 1
/gps/particle electron
/gps/number 1
/gps/direction 0 0 0.359723
/gps/ene/mono 0.155791 MeV
/gps/position 0. 0. 81.6618 m
/run/beamOn 1
/gps/particle electron
/gps/number 1
/gps/direction 0 0 0.322376
/gps/ene/mono 0.150977 MeV
/gps/position 0. 0. 85.744 m
/run/beamOn 1
/gps/particle electron
/gps/number 1
/gps/direction 0 0 0.391388
/gps/ene/mono 0.171225 MeV
/gps/position 0. 0. 116.715 m
/run/beamOn 1
/gps/particle electron
/gps/number 1
/gps/direction 0 0 0.724366
/gps/ene/mono 0.927614 MeV
/gps/position 0. 0. 118.21 m
/run/beamOn 1
/gps/particle electron
/gps/number 1
/gps/direction 0 0 0.347413
/gps/ene/mono 0.184905 MeV
/gps/position 0. 0. 166.098 m
/run/beamOn 1
/gps/particle electron
/gps/number 1
/gps/direction 0 0 0.564947
/gps/ene/mono 0.502942 MeV
/gps/position 0. 0. 185.642 m
/run/beamOn 1
/gps/particle electron
/gps/number 1
/gps/direction 0 0 0.374606
/gps/ene/mono 0.102738 MeV
/gps/position 0. 0. 186.799 m
/run/beamOn 1
/gps/particle electron
/gps/number 1
/gps/direction 0 0 0.324562
/gps/ene/mono 0.134925 MeV
/gps/position 0. 0. 204.702 m
/run/beamOn 1
/gps/particle electron
/gps/number 1
/gps/direction 0 0 0.390896
/gps/ene/mono 0.130996 MeV
/gps/position 0. 0. 205.258 m
/run/beamOn 1
/gps/particle electron
/gps/number 1
/gps/direction 0 0 0.455728
/gps/ene/mono 0.167147 MeV
/gps/position 0. 0. 212.11 m
/run/beamOn 1
/gps/particle electron
/gps/number 1
/gps/direction 0 0 0.378089
/gps/ene/mono 0.102375 MeV
/gps/position 0. 0. 213.979 m
/run/beamOn 1
/gps/particle electron
/gps/number 1
/gps/direction 0 0 0.639463
/gps/ene/mono 0.964751 MeV
/gps/position 0. 0. 245.22 m
/run/beamOn 1
/gps/particle electron
/gps/number 1
/gps/direction 0 0 0.883434
/gps/ene/mono 1.67169 MeV
/gps/position 0. 0. 263.84 m
/run/beamOn 1
/gps/particle electron
/gps/number 1
/gps/direction 0 0 0.124071
/gps/ene/mono 0.119505 MeV
/gps/position 0. 0. 275.827 m
/run/beamOn 1
/gps/particle electron
/gps/number 1
/gps/direction 0 0 0.771755
/gps/ene/mono 1.46234 MeV
/gps/position 0. 0. 339.448 m
/run/beamOn 1
/gps/particle electron
/gps/number 1
/gps/direction 0 0 0.632302
/gps/ene/mono 0.30878 MeV
/gps/position 0. 0. 180.341 m
/run/beamOn 1
/gps/particle electron
/gps/number 1
/gps/direction 0 0 0.356857
/gps/ene/mono 0.30403 MeV
/gps/position 0. 0. 232.412 m
/run/beamOn 1
/gps/particle electron
/gps/number 1
/gps/direction 0 0 -0.374995
/gps/ene/mono 0.169051 MeV
/gps/position 0. 0. -332.941 m
/run/beamOn 1
/gps/particle electron
/gps/number 1
/gps/direction 0 0 0.936398
/gps/ene/mono 0.196055 MeV
/gps/position 0. 0. 7.61122 m
/run/beamOn 1
/gps/particle electron
/gps/number 1
/gps/direction 0 0 0.11338
/gps/ene/mono 0.108148 MeV
/gps/position 0. 0. -209.933 m
/run/beamOn 1
/gps/particle electron
/gps/number 1
/gps/direction 0 0 0.044041
/gps/ene/mono 0.113329 MeV
/gps/position 0. 0. -175.18 m
/run/beamOn 1
/gps/particle electron
/gps/number 1
/gps/direction 0 0 0.499598
/gps/ene/mono 0.128761 MeV
/gps/position 0. 0. -70.7716 m
/run/beamOn 1
/gps/particle electron
/gps/number 1
/gps/direction 0 0 0.658176
/gps/ene/mono 0.316808 MeV
/gps/position 0. 0. 125.044 m
/run/beamOn 1
