/gps/particle e-
/gps/number 1
/gps/direction 0 0 0.345104
/gps/ene/mono 0.122571 MeV
/gps/position 0. 0. -306.896 m
/gps/particle e-
/gps/number 1
/gps/direction 0 0 0.447529
/gps/ene/mono 0.260309 MeV
/gps/position 0. 0. -289.969 m
/gps/particle e-
/gps/number 1
/gps/direction 0 0 0.0569382
/gps/ene/mono 0.420472 MeV
/gps/position 0. 0. -179.067 m
/gps/particle e-
/gps/number 1
/gps/direction 0 0 0.3143
/gps/ene/mono 0.157019 MeV
/gps/position 0. 0. 5.29251 m
/gps/particle e-
/gps/number 1
/gps/direction 0 0 0.742199
/gps/ene/mono 0.303701 MeV
/gps/position 0. 0. -62.2914 m
/gps/particle e-
/gps/number 1
/gps/direction 0 0 0.888456
/gps/ene/mono 0.481631 MeV
/gps/position 0. 0. -288.137 m
/gps/particle e-
/gps/number 1
/gps/direction 0 0 0.308844
/gps/ene/mono 0.147744 MeV
/gps/position 0. 0. -230.116 m
/gps/particle e-
/gps/number 1
/gps/direction 0 0 0.586606
/gps/ene/mono 0.192994 MeV
/gps/position 0. 0. -103.418 m
/gps/particle e-
/gps/number 1
/gps/direction 0 0 0.186896
/gps/ene/mono 0.124004 MeV
/gps/position 0. 0. -97.4243 m
/gps/particle e-
/gps/number 1
/gps/direction 0 0 0.858496
/gps/ene/mono 3.06733 MeV
/gps/position 0. 0. -83.0766 m
/gps/particle e-
/gps/number 1
/gps/direction 0 0 0.985092
/gps/ene/mono 11.1833 MeV
/gps/position 0. 0. -79.0316 m
/gps/particle e-
/gps/number 1
/gps/direction 0 0 0.408826
/gps/ene/mono 0.142927 MeV
/gps/position 0. 0. 34.1317 m
/gps/particle e-
/gps/number 1
/gps/direction 0 0 0.313608
/gps/ene/mono 0.102928 MeV
/gps/position 0. 0. 115.631 m
/gps/particle e-
/gps/number 1
/gps/direction 0 0 0.497374
/gps/ene/mono 0.200037 MeV
/gps/position 0. 0. 180.974 m
/gps/particle e-
/gps/number 1
/gps/direction 0 0 0.452874
/gps/ene/mono 0.118198 MeV
/gps/position 0. 0. 220.668 m
/gps/particle e-
/gps/number 1
/gps/direction 0 0 0.523039
/gps/ene/mono 0.37954 MeV
/gps/position 0. 0. 229.053 m
/gps/particle e-
/gps/number 1
/gps/direction 0 0 0.270327
/gps/ene/mono 0.101533 MeV
/gps/position 0. 0. 272.763 m
/gps/particle e-
/gps/number 1
/gps/direction 0 0 0.387253
/gps/ene/mono 0.156262 MeV
/gps/position 0. 0. 276.185 m
/gps/particle e-
/gps/number 1
/gps/direction 0 0 0.651252
/gps/ene/mono 0.987603 MeV
/gps/position 0. 0. 280.07 m
/gps/particle e-
/gps/number 1
/gps/direction 0 0 0.37174
/gps/ene/mono 0.116118 MeV
/gps/position 0. 0. 285.816 m
/gps/particle e-
/gps/number 1
/gps/direction 0 0 0.442625
/gps/ene/mono 0.177245 MeV
/gps/position 0. 0. 306.189 m
/gps/particle e-
/gps/number 1
/gps/direction 0 0 0.484165
/gps/ene/mono 0.360448 MeV
/gps/position 0. 0. 334.898 m
/gps/particle e-
/gps/number 1
/gps/direction 0 0 0.348236
/gps/ene/mono 0.12677 MeV
/gps/position 0. 0. 349.051 m
/gps/particle e-
/gps/number 1
/gps/direction 0 0 0.986776
/gps/ene/mono 4.34404 MeV
/gps/position 0. 0. 304.439 m
/gps/particle e-
/gps/number 1
/gps/direction 0 0 0.668806
/gps/ene/mono 0.270452 MeV
/gps/position 0. 0. -183.383 m
/gps/particle e-
/gps/number 1
/gps/direction 0 0 0.322662
/gps/ene/mono 0.206126 MeV
/gps/position 0. 0. 136.018 m
/gps/particle e-
/gps/number 1
/gps/direction 0 0 0.651335
/gps/ene/mono 0.231161 MeV
/gps/position 0. 0. -212.346 m
/gps/particle e-
/gps/number 1
/gps/direction 0 0 0.490181
/gps/ene/mono 0.138673 MeV
/gps/position 0. 0. -142.166 m
/gps/particle e-
/gps/number 1
/gps/direction 0 0 0.206412
/gps/ene/mono 0.191916 MeV
/gps/position 0. 0. -126.008 m
/gps/particle e-
/gps/number 1
/gps/direction 0 0 0.195678
/gps/ene/mono 0.121023 MeV
/gps/position 0. 0. -119.814 m
/gps/particle e-
/gps/number 1
/gps/direction 0 0 0.0852502
/gps/ene/mono 0.164655 MeV
/gps/position 0. 0. -91.3947 m
/gps/particle e-
/gps/number 1
/gps/direction 0 0 0.613168
/gps/ene/mono 0.204745 MeV
/gps/position 0. 0. -55.8298 m
/gps/particle e-
/gps/number 1
/gps/direction 0 0 0.76154
/gps/ene/mono 1.53549 MeV
/gps/position 0. 0. -54.9255 m
/gps/particle e-
/gps/number 1
/gps/direction 0 0 0.424683
/gps/ene/mono 0.145849 MeV
/gps/position 0. 0. -51.5841 m
/gps/particle e-
/gps/number 1
/gps/direction 0 0 0.5842
/gps/ene/mono 1.52031 MeV
/gps/position 0. 0. -49.6746 m
/gps/particle e-
/gps/number 1
/gps/direction 0 0 0.0712965
/gps/ene/mono 0.105381 MeV
/gps/position 0. 0. -6.77063 m
/gps/particle e-
/gps/number 1
/gps/direction 0 0 0.644081
/gps/ene/mono 0.265181 MeV
/gps/position 0. 0. 1.9003 m
/gps/particle e-
/gps/number 1
/gps/direction 0 0 0.530223
/gps/ene/mono 0.265428 MeV
/gps/position 0. 0. 31.3542 m
/gps/particle e-
/gps/number 1
/gps/direction 0 0 0.227017
/gps/ene/mono 0.121199 MeV
/gps/position 0. 0. 34.0319 m
/gps/particle e-
/gps/number 1
/gps/direction 0 0 0.551705
/gps/ene/mono 0.232209 MeV
/gps/position 0. 0. 102.882 m
/gps/particle e-
/gps/number 1
/gps/direction 0 0 0.251527
/gps/ene/mono 0.128816 MeV
/gps/position 0. 0. 148.69 m
/gps/particle e-
/gps/number 1
/gps/direction 0 0 0.332354
/gps/ene/mono 0.140226 MeV
/gps/position 0. 0. 168.372 m
/gps/particle e-
/gps/number 1
/gps/direction 0 0 0.242706
/gps/ene/mono 0.14825 MeV
/gps/position 0. 0. 175.34 m
/gps/particle e-
/gps/number 1
/gps/direction 0 0 0.180867
/gps/ene/mono 0.164115 MeV
/gps/position 0. 0. 271.715 m
/gps/particle e-
/gps/number 1
/gps/direction 0 0 0.401425
/gps/ene/mono 0.442787 MeV
/gps/position 0. 0. 281.37 m
/gps/particle e-
/gps/number 1
/gps/direction 0 0 0.157123
/gps/ene/mono 0.219784 MeV
/gps/position 0. 0. -291.005 m
/gps/particle e-
/gps/number 1
/gps/direction 0 0 0.316366
/gps/ene/mono 0.443985 MeV
/gps/position 0. 0. -183.683 m
/gps/particle e-
/gps/number 1
/gps/direction 0 0 0.507276
/gps/ene/mono 0.366705 MeV
/gps/position 0. 0. -141.295 m
/gps/particle e-
/gps/number 1
/gps/direction 0 0 0.336358
/gps/ene/mono 0.107017 MeV
/gps/position 0. 0. -108.407 m
/gps/particle e-
/gps/number 1
/gps/direction 0 0 0.178035
/gps/ene/mono 0.19222 MeV
/gps/position 0. 0. -56.03 m
/gps/particle e-
/gps/number 1
/gps/direction 0 0 0.229365
/gps/ene/mono 0.243683 MeV
/gps/position 0. 0. -25.4689 m
/gps/particle e-
/gps/number 1
/gps/direction 0 0 0.437591
/gps/ene/mono 0.149929 MeV
/gps/position 0. 0. 97.9023 m
/gps/particle e-
/gps/number 1
/gps/direction 0 0 0.668611
/gps/ene/mono 0.511991 MeV
/gps/position 0. 0. 153.451 m
/gps/particle e-
/gps/number 1
/gps/direction 0 0 0.671977
/gps/ene/mono 0.291572 MeV
/gps/position 0. 0. 172.352 m
/gps/particle e-
/gps/number 1
/gps/direction 0 0 0.392416
/gps/ene/mono 0.56263 MeV
/gps/position 0. 0. 192.503 m
/gps/particle e-
/gps/number 1
/gps/direction 0 0 0.440986
/gps/ene/mono 0.187489 MeV
/gps/position 0. 0. 219.004 m
/gps/particle e-
/gps/number 1
/gps/direction 0 0 0.338299
/gps/ene/mono 0.117749 MeV
/gps/position 0. 0. 271.893 m
/gps/particle e-
/gps/number 1
/gps/direction 0 0 0.945779
/gps/ene/mono 1.19431 MeV
/gps/position 0. 0. -59.8516 m
/gps/particle e-
/gps/number 1
/gps/direction 0 0 0.844795
/gps/ene/mono 0.938978 MeV
/gps/position 0. 0. 331.229 m
/gps/particle e-
/gps/number 1
/gps/direction 0 0 0.919077
/gps/ene/mono 0.255419 MeV
/gps/position 0. 0. -36.118 m
/gps/particle e-
/gps/number 1
/gps/direction 0 0 -0.672288
/gps/ene/mono 0.138809 MeV
/gps/position 0. 0. -295.901 m
/gps/particle e-
/gps/number 1
/gps/direction 0 0 0.0597394
/gps/ene/mono 0.417494 MeV
/gps/position 0. 0. -269.558 m
/gps/particle e-
/gps/number 1
/gps/direction 0 0 0.242037
/gps/ene/mono 0.436078 MeV
/gps/position 0. 0. -226.145 m
/gps/particle e-
/gps/number 1
/gps/direction 0 0 0.395658
/gps/ene/mono 0.281489 MeV
/gps/position 0. 0. -206.06 m
/gps/particle e-
/gps/number 1
/gps/direction 0 0 0.705801
/gps/ene/mono 0.217921 MeV
/gps/position 0. 0. -193.599 m
/gps/particle e-
/gps/number 1
/gps/direction 0 0 0.609702
/gps/ene/mono 0.263367 MeV
/gps/position 0. 0. -134.16 m
/gps/particle e-
/gps/number 1
/gps/direction 0 0 0.201313
/gps/ene/mono 0.19862 MeV
/gps/position 0. 0. -131.223 m
/gps/particle e-
/gps/number 1
/gps/direction 0 0 0.155593
/gps/ene/mono 0.208806 MeV
/gps/position 0. 0. -45.4697 m
/gps/particle e-
/gps/number 1
/gps/direction 0 0 0.618873
/gps/ene/mono 0.783988 MeV
/gps/position 0. 0. 27.9024 m
/gps/particle e-
/gps/number 1
/gps/direction 0 0 0.39683
/gps/ene/mono 0.225618 MeV
/gps/position 0. 0. 86.8398 m
/gps/particle e-
/gps/number 1
/gps/direction 0 0 0.539471
/gps/ene/mono 0.285468 MeV
/gps/position 0. 0. 108.162 m
/gps/particle e-
/gps/number 1
/gps/direction 0 0 0.255146
/gps/ene/mono 0.120508 MeV
/gps/position 0. 0. 109.446 m
/gps/particle e-
/gps/number 1
/gps/direction 0 0 0.688967
/gps/ene/mono 0.579098 MeV
/gps/position 0. 0. 118.881 m
/gps/particle e-
/gps/number 1
/gps/direction 0 0 0.382603
/gps/ene/mono 0.264793 MeV
/gps/position 0. 0. 142.979 m
/gps/particle e-
/gps/number 1
/gps/direction 0 0 0.305075
/gps/ene/mono 0.133439 MeV
/gps/position 0. 0. 153.255 m
/gps/particle e-
/gps/number 1
/gps/direction 0 0 0.394291
/gps/ene/mono 0.102302 MeV
/gps/position 0. 0. 178.225 m
/gps/particle e-
/gps/number 1
/gps/direction 0 0 0.277342
/gps/ene/mono 0.152883 MeV
/gps/position 0. 0. 204.734 m
/gps/particle e-
/gps/number 1
/gps/direction 0 0 0.653763
/gps/ene/mono 1.0571 MeV
/gps/position 0. 0. 213.288 m
/gps/particle e-
/gps/number 1
/gps/direction 0 0 0.637621
/gps/ene/mono 0.526417 MeV
/gps/position 0. 0. 257.31 m
/gps/particle e-
/gps/number 1
/gps/direction 0 0 0.3889
/gps/ene/mono 0.146989 MeV
/gps/position 0. 0. 275.808 m
/gps/particle e-
/gps/number 1
/gps/direction 0 0 0.453996
/gps/ene/mono 0.27311 MeV
/gps/position 0. 0. 337.131 m
/gps/particle e-
/gps/number 1
/gps/direction 0 0 0.525041
/gps/ene/mono 0.213713 MeV
/gps/position 0. 0. -213.518 m
/gps/particle e-
/gps/number 1
/gps/direction 0 0 -0.132882
/gps/ene/mono 0.333242 MeV
/gps/position 0. 0. -301.339 m
/gps/particle e-
/gps/number 1
/gps/direction 0 0 0.426087
/gps/ene/mono 0.222214 MeV
/gps/position 0. 0. -125.772 m
